### ISSUE TITLE
Java websocket client does not handle end of input after broker closes connection

### ISSUE THREAD

**Issue by jpwsutton** [eclipse/paho.mqtt.android#1]
migrated from Bugzilla [#488345](https://bugs.eclipse.org/bugs/show_bug.cgi?id=488345)
status UNCONFIRMED severity *major* in component *MQTT-Android* for *1.2*
Reported in version *future* on platform *Macintosh*
Assigned to: James Sutton

On 2016-02-23 21:05:25 -0500, Vineet Dixit wrote:

> Java Websocket client throws IO exception due to error shown below when broker closes the connection. This is observed on the development branch org.eclipse.paho.client.mqttv3-1.0.3-SNAPSHOT.jar. Some details are included in this thread https://www.eclipse.org/forums/index.php/t/1075009/
> 
> Publishing at: 2016-02-22 22:59:03.496 to topic "mqtt/demo" qos 2
> WebSocketReceiver.java : run(): Exception Occured.
> java.io.IOException: Invalid Frame: Opcode: 15
> at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketFrame.<init>(WebSocketFrame.java:187)
> at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketReceiver.run(WebSocketReceiver.java:98)
> at java.lang.Thread.run(Thread.java:745)
> Disconnected

**Comment by jpwsutton** [comment]
This is actually a bug in the Java Client, So I've raised the bug here: https://github.com/eclipse/paho.mqtt.java/issues/177
