### ISSUE TITLE
NPE on CONNECTIVITY_CHANGE event

### ISSUE THREAD

**Issue by baole** [eclipse/paho.mqtt.android#101]
Please fill out the form below before submitting, thank you!
- [x] Bug exists Release Version 1.1.0 (Java Repository Master Branch)
- [x] Bug exists in Snapshot Version 1.1.1-SNAPSHOT (Android Service Repository Master Branch)
- [ ] Bug is just in the Sample Application.

**Android API Version Bug Seen on:**

**Android Version Bug Seen on:**

Android 4, 5, 6
## Description of Bug:

This bug is reported on this ticket with closed status: https://github.com/eclipse/paho.mqtt.android/issues/81 
## Console Log output (if available):

This is crashes reported on Fabric:  http://crashes.to/s/4b5e49649ff

**Comment by baole** [comment]
As this NPE is not sent back to the application, is there any workaround to avoid the app crashes?

**Comment by jpwsutton** [comment]
Not sure yet, your Crash is subtly different from the one you linked to. 
Full Stack Trace:
```
Fatal Exception: java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4000010 (has extras) } in org.eclipse.paho.android.service.MqttService$NetworkConnectionIntentReceiver@41ee9dd8
       at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:769)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5122)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by java.lang.NullPointerException
       at org.eclipse.paho.android.service.MqttConnection.reconnect(Unknown Source:1064)
       at org.eclipse.paho.android.service.MqttService.reconnect(Unknown Source:343)
       at org.eclipse.paho.android.service.MqttService$NetworkConnectionIntentReceiver.onReceive(Unknown Source:826)
       at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:759)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5122)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
       at dalvik.system.NativeStart.main(NativeStart.java)```

This looks like this line is throwing the null pointer: https://github.com/eclipse/paho.mqtt.android/blob/develop/org.eclipse.paho.android.service/src/main/java/org/eclipse/paho/android/service/MqttConnection.java#L1064

Quite how myClient was null at this point is a bit odd. I can add a null check in there which will assume that the client could not connect and will return back up to the App as a normal MqttException. 

How it became null is of interest to me, are you able to recreate this on a test device with logging enabled? What are the circumstances leading up until the connectivity change?

**Comment by baole** [comment]
Hi jpwsutton,

I agree with you that myClient is null which leads to the NPE. Unfortunately, I could not reproduce this crash on my test environment. If the NPE is thrown back to the application level, the application can do a fresh connect again as a workaround.

**Comment by jpwsutton** [comment]
Ok, I've added in an extra catch to pass this exception up to the application. I'd like to get to the root cause of myClient being null though so I'll leave this bug open so if anyone is able to recreate this then they can leave details here

**Comment by baole** [comment]
Thanks @jpwsutton, I just updated my app on Playstore with this workaround and see if the issue is fixed.

**Comment by baole** [comment]
FYI, the workaround works

**Comment by jpwsutton** [comment]
@baole Thanks for letting us know, glad it worked. If you see anything that could explain how myClient became null, we'd be glad to hear about it.

**Comment by jotish** [comment]
https://github.com/eclipse/paho.mqtt.android/issues/159

**Comment by jotish** [comment]
@jpwsutton Due date for 1.3.0 ? We will use the workaround as well.

**Comment by jpwsutton** [comment]
@jotish It's going to be sometime in the new year I think, we (the Paho Committers) need to decide on what will be going into it first before we can decide on a target date.
