### ISSUE TITLE
Offline buffering not working

### ISSUE THREAD

**Issue by binarybucks** [eclipse/paho.mqtt.android#102]
Please fill out the form below before submitting, thank you!

- [ ] Bug exists Release Version 1.1.0 (Java Repository Master Branch)
- [x] Bug exists in Snapshot Version 1.1.1-SNAPSHOT (Android Service Repository Master Branch)
- [ ] Bug is just in the Sample Application.

__Android API Version Bug Seen on:__
23

__Android Version Bug Seen on:__
6.0 (emulator)

Please also check that if you have found the bug in the Release version (1.1.0) that you check that it also exists in the Snapshot (1.1.1-SNAPSHOT) before raising a bug.

## Description of Bug:
I'm trying to implement offline buffering for OwnTracks using the latest 1.1.1-SNAPSHOT but publishing messages while not connected always throws `Client is not connected (32104)` instead of buffering the message. 

Relevant code: 

Assembling connect options and connecting
```
MqttConnectOptions options = new MqttConnectOptions();
options.setAutomaticReconnect(true);


this.client = new MqttAndroidClient(context, getConnectUri(), getConnectClientId());
client.connect(options , null, iCallbackConnection);
```

Connection callback and setting disconnectedBufferOptions

```
    private IMqttActionListener iCallbackConnection = new IMqttActionListener() {

        @Override
        public void onSuccess(IMqttToken asyncActionToken) {
            this.disconnectedBufferOptions = new DisconnectedBufferOptions();
            this.disconnectedBufferOptions.setBufferEnabled(true);
            this.disconnectedBufferOptions.setBufferSize(1024);
            this.disconnectedBufferOptions.setPersistBuffer(false);
            this.disconnectedBufferOptions.setDeleteOldestMessages(true);

            client.setBufferOpts(disconnectedBufferOptions);
            subscribe();
        }

    };

```

Calling `client.publish(...)` after the `connectionLost` Callback of the client is invoked, results in the stacktrace below. Judging from the Code in ClientComms, the following line is true `disconnectedMessageBuffer != null && isResting()`. 

Can you give me any hint if my implementation is wrong or if this is a bug? 

## Console Log output (if available):
```
PubCallback onFailure
Client is not connected (32104)
    at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:31)
    at org.eclipse.paho.client.mqttv3.internal.ClientComms.sendNoWait(ClientComms.java:166)
    at org.eclipse.paho.client.mqttv3.MqttAsyncClient.publish(MqttAsyncClient.java:1027)
    at org.eclipse.paho.android.service.MqttConnection.publish(MqttConnection.java:591)
    at org.eclipse.paho.android.service.MqttService.publish(MqttService.java:469)
    at org.eclipse.paho.android.service.MqttAndroidClient.publish(MqttAndroidClient.java:824)
    at org.eclipse.paho.android.service.MqttAndroidClient.publish(MqttAndroidClient.java:680)
    at org.owntracks.android.services.ServiceMessageMqttExperimental.publishMessage(ServiceMessageMqttExperimental.java:403)
    at org.owntracks.android.services.ServiceMessageMqttExperimental.processMessage(ServiceMessageMqttExperimental.java:454)
    at org.owntracks.android.messages.MessageLocation.processOutgoingMessage(MessageLocation.java:130)
    at org.owntracks.android.messages.MessageBase.run(MessageBase.java:105)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
    at java.lang.Thread.run(Thread.java:818)
```

**Comment by jpwsutton** [comment]
Your implementation looks good to me, and is what I did in the paho.mqtt.android.example app. Does the example app work for you?

**Comment by binarybucks** [comment]
I'd like to build the example, but I've not been able to build it yet. Any pointers? 
The project has been imported into Android Studio according to the readme. 

```
Information:Gradle tasks [:org.eclipse.paho.android.sample:assembleDebug]
No SDK tools available for update.
Copying MQTT Jar into libs directory
No SDK tools available for update.
:org.eclipse.paho.android.sample:preBuild UP-TO-DATE
:org.eclipse.paho.android.sample:preDebugBuild UP-TO-DATE
:org.eclipse.paho.android.sample:checkDebugManifest
:org.eclipse.paho.android.sample:preReleaseBuild UP-TO-DATE
:org.eclipse.paho.android.service:preBuild UP-TO-DATE
:org.eclipse.paho.android.service:preReleaseBuild UP-TO-DATE
:org.eclipse.paho.android.service:compileReleaseNdk UP-TO-DATE
:org.eclipse.paho.android.service:compileLint
:org.eclipse.paho.android.service:copyReleaseLint UP-TO-DATE
:org.eclipse.paho.android.service:checkReleaseManifest
:org.eclipse.paho.android.service:preDebugAndroidTestBuild UP-TO-DATE
:org.eclipse.paho.android.service:preDebugBuild UP-TO-DATE
:org.eclipse.paho.android.service:preDebugUnitTestBuild UP-TO-DATE
:org.eclipse.paho.android.service:preReleaseUnitTestBuild UP-TO-DATE
:org.eclipse.paho.android.service:prepareComAndroidSupportSupportV42330Library UP-TO-DATE
:org.eclipse.paho.android.service:prepareReleaseDependencies
:org.eclipse.paho.android.service:compileReleaseAidl UP-TO-DATE
:org.eclipse.paho.android.service:compileReleaseRenderscript UP-TO-DATE
:org.eclipse.paho.android.service:generateReleaseBuildConfig UP-TO-DATE
:org.eclipse.paho.android.service:generateReleaseAssets UP-TO-DATE
:org.eclipse.paho.android.service:mergeReleaseAssets UP-TO-DATE
:org.eclipse.paho.android.service:generateReleaseResValues UP-TO-DATE
:org.eclipse.paho.android.service:generateReleaseResources UP-TO-DATE
:org.eclipse.paho.android.service:mergeReleaseResources UP-TO-DATE
:org.eclipse.paho.android.service:processReleaseManifest UP-TO-DATE
:org.eclipse.paho.android.service:processReleaseResources UP-TO-DATE
:org.eclipse.paho.android.service:generateReleaseSources UP-TO-DATE
:org.eclipse.paho.android.service:compileReleaseJavaWithJavac UP-TO-DATE
:org.eclipse.paho.android.service:extractReleaseAnnotations UP-TO-DATE
:org.eclipse.paho.android.service:mergeReleaseProguardFiles UP-TO-DATE
:org.eclipse.paho.android.service:packageReleaseRenderscript UP-TO-DATE
:org.eclipse.paho.android.service:packageReleaseResources UP-TO-DATE
:org.eclipse.paho.android.service:processReleaseJavaRes UP-TO-DATE
:org.eclipse.paho.android.service:transformResourcesWithMergeJavaResForRelease UP-TO-DATE
:org.eclipse.paho.android.service:transformClassesAndResourcesWithSyncLibJarsForRelease UP-TO-DATE
:org.eclipse.paho.android.service:mergeReleaseJniLibFolders UP-TO-DATE
:org.eclipse.paho.android.service:transformNative_libsWithMergeJniLibsForRelease UP-TO-DATE
:org.eclipse.paho.android.service:transformNative_libsWithSyncJniLibsForRelease UP-TO-DATE
:org.eclipse.paho.android.service:bundleRelease UP-TO-DATE
:org.eclipse.paho.android.sample:prepareComAndroidSupportAnimatedVectorDrawable2330Library UP-TO-DATE
:org.eclipse.paho.android.sample:prepareComAndroidSupportAppcompatV72330Library UP-TO-DATE
:org.eclipse.paho.android.sample:prepareComAndroidSupportRecyclerviewV72330Library UP-TO-DATE
:org.eclipse.paho.android.sample:prepareComAndroidSupportSupportV42330Library UP-TO-DATE
:org.eclipse.paho.android.sample:prepareComAndroidSupportSupportVectorDrawable2330Library UP-TO-DATE
:org.eclipse.paho.android.sample:prepareOrgEclipsePahoOrgEclipsePahoAndroidService110Library UP-TO-DATE
:org.eclipse.paho.android.sample:prepareDebugDependencies
:org.eclipse.paho.android.sample:compileDebugAidl UP-TO-DATE
:org.eclipse.paho.android.sample:compileDebugRenderscript UP-TO-DATE
:org.eclipse.paho.android.sample:generateDebugBuildConfig UP-TO-DATE
:org.eclipse.paho.android.sample:generateDebugAssets UP-TO-DATE
:org.eclipse.paho.android.sample:mergeDebugAssets UP-TO-DATE
:org.eclipse.paho.android.sample:generateDebugResValues UP-TO-DATE
:org.eclipse.paho.android.sample:generateDebugResources UP-TO-DATE
:org.eclipse.paho.android.sample:mergeDebugResources UP-TO-DATE
:org.eclipse.paho.android.sample:processDebugManifest UP-TO-DATE
:org.eclipse.paho.android.sample:processDebugResources UP-TO-DATE
:org.eclipse.paho.android.sample:generateDebugSources UP-TO-DATE
:org.eclipse.paho.android.sample:compileDebugJavaWithJavac
C:\Users\alexander\Documents\Code\paho.mqtt.android\org.eclipse.paho.android.sample\src\main\java\org\eclipse\paho\android\sample\model\ReceivedMessage.java
Error:(9, 42) error: cannot find symbol class MqttMessage
Error:(16, 5) error: cannot find symbol class MqttMessage
Error:(23, 12) error: cannot find symbol class MqttMessage
C:\Users\alexander\Documents\Code\paho.mqtt.android\org.eclipse.paho.android.sample\src\main\java\org\eclipse\paho\android\sample\activity\ActionListener.java
Error:(11, 38) error: package org.eclipse.paho.client.mqttv3 does not exist
Error:(12, 38) error: package org.eclipse.paho.client.mqttv3 does not exist
Error:(13, 38) error: package org.eclipse.paho.client.mqttv3 does not exist
Error:(22, 40) error: cannot find symbol class IMqttActionListener
Error:(93, 27) error: cannot find symbol class IMqttToken
Error:(191, 27) error: cannot find symbol class IMqttToken
Error:(92, 5) error: method does not override or implement a method from a supertype
Error:(176, 39) error: cannot access IMqttAsyncClient
class file for org.eclipse.paho.client.mqttv3.IMqttAsyncClient not found
Error:(178, 18) error: cannot find symbol class MqttException
Error:(190, 5) error: method does not override or implement a method from a supertype
C:\Users\alexander\Documents\Code\paho.mqtt.android\org.eclipse.paho.android.sample\src\main\java\org\eclipse\paho\android\sample\activity\Connection.java
Error:(16, 38) error: package org.eclipse.paho.client.mqttv3 does not exist
Error:(17, 38) error: package org.eclipse.paho.client.mqttv3 does not exist
Error:(18, 38) error: package org.eclipse.paho.client.mqttv3 does not exist
Error:(68, 13) error: cannot find symbol class MqttConnectOptions
Error:(346, 38) error: cannot find symbol class MqttConnectOptions
Error:(355, 12) error: cannot find symbol class MqttConnectOptions
Error:(426, 70) error: cannot find symbol class MqttException
Error:(447, 64) error: cannot find symbol class MqttException
Error:(473, 46) error: cannot find symbol class MqttMessage
Error:(433, 33) error: cannot access IMqttActionListener
class file for org.eclipse.paho.client.mqttv3.IMqttActionListener not found
Error:(440, 27) error: cannot find symbol class MqttException
Error:(449, 41) error: cannot access IMqttToken
class file for org.eclipse.paho.client.mqttv3.IMqttToken not found
C:\Users\alexander\Documents\Code\paho.mqtt.android\org.eclipse.paho.android.sample\src\main\java\org\eclipse\paho\android\sample\activity\MainActivity.java
Error:(276, 13) error: cannot find symbol class MqttConnectOptions
Error:(202, 48) error: incompatible types: MqttCallbackHandler cannot be converted to MqttCallback
Error:(205, 13) error: cannot find symbol class MqttConnectOptions
Error:(219, 18) error: cannot find symbol class MqttException
Error:(241, 44) error: incompatible types: MqttCallbackHandler cannot be converted to MqttCallback
Error:(247, 9) error: cannot find symbol class MqttConnectOptions
Error:(265, 16) error: cannot find symbol class MqttException
Error:(278, 9) error: cannot find symbol class MqttConnectOptions
Error:(278, 43) error: cannot find symbol class MqttConnectOptions
Error:(307, 44) error: incompatible types: MqttCallbackHandler cannot be converted to MqttCallback
Error:(311, 16) error: cannot find symbol class MqttException
Error:(321, 18) error: cannot find symbol class MqttException
Error:(334, 90) error: incompatible types: ActionListener cannot be converted to IMqttActionListener
Error:(335, 18) error: cannot find symbol class MqttException
Error:(348, 18) error: cannot find symbol class MqttException
C:\Users\alexander\Documents\Code\paho.mqtt.android\org.eclipse.paho.android.sample\src\main\java\org\eclipse\paho\android\sample\activity\MqttCallbackHandler.java
Error:(22, 38) error: package org.eclipse.paho.client.mqttv3 does not exist
Error:(23, 38) error: package org.eclipse.paho.client.mqttv3 does not exist
Error:(30, 45) error: cannot find symbol class MqttCallback
Error:(78, 44) error: cannot find symbol class MqttMessage
Error:(97, 32) error: cannot find symbol class IMqttDeliveryToken
Error:(54, 3) error: method does not override or implement a method from a supertype
Error:(77, 3) error: method does not override or implement a method from a supertype
Error:(96, 3) error: method does not override or implement a method from a supertype
C:\Users\alexander\Documents\Code\paho.mqtt.android\org.eclipse.paho.android.sample\src\main\java\org\eclipse\paho\android\sample\activity\SubscriptionFragment.java
Error:(82, 26) error: cannot find symbol class MqttException
Error:(131, 26) error: cannot find symbol class MqttException
C:\Users\alexander\Documents\Code\paho.mqtt.android\org.eclipse.paho.android.sample\src\main\java\org\eclipse\paho\android\sample\internal\Persistence.java
Error:(203, 9) error: cannot find symbol class MqttConnectOptions
Error:(204, 9) error: cannot find symbol class MqttMessage
Error:(351, 13) error: cannot find symbol class MqttConnectOptions
Error:(351, 43) error: cannot find symbol class MqttConnectOptions
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
Error:Execution failed for task ':org.eclipse.paho.android.sample:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
Information:BUILD FAILED
Information:Total time: 8.596 secs
Information:55 errors
Information:0 warnings
Information:See complete output in console
```

**Comment by jpwsutton** [comment]
That's odd, I've cloned the develop branch into a clean workspace, opened it in Android Studio and clicked the Build button with the Sample project selected. The Build completed with no issued and the app ran on my connected phone, I tried building from the command line as well which also worked..

The errors look to me like the build can't find the base ```org.eclipse.paho:org.eclipse.paho.client.mqttv3``` Java client that the Android service runs on top of, this should be pulled down from repo.eclipse.org.

Could you try manually downloading the jar from here: https://repo.eclipse.org/content/repositories/paho-snapshots/org/eclipse/paho/org.eclipse.paho.client.mqttv3/1.1.1-SNAPSHOT/ and then forcing the Sample project dependencies to use that jar? (The snapshot builds are a bit old as we are having trouble with the build due to a renewed SSL certificate at the moment, but nothing has changed in that branch for a while so should be ok)

**Comment by yon86** [comment]
for me when the mqttAndroidClient is not connected I get null reference error when trying to get the buffered messages count as in the example 
``` mqttAndroidClient.getBufferedMessageCount(); ```

**Comment by kartben** [comment]
I ran into the same issue as @binarybucks and fixed it via: http://stackoverflow.com/questions/33404552/execution-failed-for-task-appcompiledebugjavawithjavac-in-android-studio

**Comment by kartben** [comment]
This seems to be due to:
```
configurations.compile.exclude module: 'org.eclipse.paho.client.mqttv3'
```
in `paho.mqtt.android.example/build.gradle`? Commenting this out fixes the problem for me.
