### ISSUE TITLE
Resource leak report in strict mode: connection is not released properly

### ISSUE THREAD

**Issue by mingchen** [eclipse/paho.mqtt.android#130]
Please fill out the form below before submitting, thank you!

- [x] Bug exists Release Version 1.1.0 (Java Repository Master Branch)
- [ ] Bug exists in Snapshot Version 1.1.1-SNAPSHOT (Android Service Repository Master Branch)
- [ ] Bug is just in the Sample Application.

__Android API Version Bug Seen on:__
6.0

__Android Version Bug Seen on:__

Please also check that if you have found the bug in the Release version (1.1.0) that you check that it also exists in the Snapshot (1.1.1-SNAPSHOT) before raising a bug.

## Description of Bug:
Resource leak report in strict mode: connection is not released properly

## Console Log output (if available):

      E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
      java.lang.Throwable: Explicit termination method 'close' not called
      at dalvik.system.CloseGuard.open(CloseGuard.java:180)
      at java.io.RandomAccessFile.<init>(RandomAccessFile.java:127)
      at org.eclipse.paho.client.mqttv3.internal.FileLock.<init>(FileLock.java:49)
      at org.eclipse.paho.client.mqttv3.persist.MqttDefaultFilePersistence.open(MqttDefaultFilePersistence.java:110)
      at org.eclipse.paho.client.mqttv3.internal.ConnectActionListener.connect(ConnectActionListener.java:175)
      at org.eclipse.paho.client.mqttv3.MqttAsyncClient.connect(MqttAsyncClient.java:592)
      at org.eclipse.paho.client.mqttv3.MqttAsyncClient.attemptReconnect(MqttAsyncClient.java:1078)
      at org.eclipse.paho.client.mqttv3.MqttAsyncClient.access$2(MqttAsyncClient.java:1073)
      at org.eclipse.paho.client.mqttv3.MqttAsyncClient$ReconnectTask.run(MqttAsyncClient.java:1138)
      at java.util.Timer$TimerImpl.run(Timer.java:284)

      E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
      java.lang.Throwable: Explicit termination method 'close' not called
      at dalvik.system.CloseGuard.open(CloseGuard.java:180)
      at java.io.RandomAccessFile.<init>(RandomAccessFile.java:127)
      at org.eclipse.paho.client.mqttv3.internal.FileLock.<init>(FileLock.java:49)
      at org.eclipse.paho.client.mqttv3.persist.MqttDefaultFilePersistence.open(MqttDefaultFilePersistence.java:110)
      at org.eclipse.paho.client.mqttv3.internal.ConnectActionListener.connect(ConnectActionListener.java:175)
      at org.eclipse.paho.client.mqttv3.internal.ConnectActionListener.onFailure(ConnectActionListener.java:138)
      at org.eclipse.paho.client.mqttv3.internal.CommsCallback.fireActionEvent(CommsCallback.java:303)
      at org.eclipse.paho.client.mqttv3.internal.CommsCallback.handleActionComplete(CommsCallback.java:237)
      at org.eclipse.paho.client.mqttv3.internal.CommsCallback.asyncOperationComplete(CommsCallback.java:422)
      at org.eclipse.paho.client.mqttv3.internal.ClientComms.shutdownConnection(ClientComms.java:380)
      at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:668)
      at java.lang.Thread.run(Thread.java:818)

      E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
      java.lang.Throwable: Explicit termination method 'close' not called
      at dalvik.system.CloseGuard.open(CloseGuard.java:180)
      at java.io.RandomAccessFile.<init>(RandomAccessFile.java:127)
      at org.eclipse.paho.client.mqttv3.internal.FileLock.<init>(FileLock.java:49)
      at org.eclipse.paho.client.mqttv3.persist.MqttDefaultFilePersistence.open(MqttDefaultFilePersistence.java:110)
      at org.eclipse.paho.client.mqttv3.internal.ConnectActionListener.connect(ConnectActionListener.java:175)
      at org.eclipse.paho.client.mqttv3.MqttAsyncClient.connect(MqttAsyncClient.java:592)
      at org.eclipse.paho.android.service.MqttConnection.connect(MqttConnection.java:295)
      at org.eclipse.paho.android.service.MqttService.connect(MqttService.java:330)
      at org.eclipse.paho.android.service.MqttAndroidClient.doConnect(MqttAndroidClient.java:474)
      at org.eclipse.paho.android.service.MqttAndroidClient.access$200(MqttAndroidClient.java:77)
      at org.eclipse.paho.android.service.MqttAndroidClient$MyServiceConnection.onServiceConnected(MqttAndroidClient.java:116)
      at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1223)
      at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1240)
      at android.os.Handler.handleCallback(Handler.java:739)
      at android.os.Handler.dispatchMessage(Handler.java:95)
      at android.os.Looper.loop(Looper.java:148)
      at android.app.ActivityThread.main(ActivityThread.java:5417)
      at java.lang.reflect.Method.invoke(Native Method)
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by jpwsutton** [comment]
Hi, I'd not tried using strict mode in the past, thanks for raising this.
I can see quite a few issues, that seem to revolve around access to the file system for the persistence layer.

However I couldn't recreate your error logs. Could you post the Strict mode config you used as well as steps to recreate in the Example app please?

For example, I've tried with:

```
StrictMode.setThreadPolicy(new StrictMode.ThreadPolicy.Builder()
                .detectDiskReads()
                .detectDiskWrites()
                .detectNetwork()
                .penaltyLog()
                .penaltyDialog()
                .build());
        StrictMode.setVmPolicy(new StrictMode.VmPolicy.Builder().detectAll()
                .penaltyLog()
                .build());
```

Once we have a clear idea of what we're working with, I'll look into resolving any issues that are picked up by strict mode.
