### ISSUE TITLE
NullPointerException in MqttConnection.reconnect

### ISSUE THREAD

**Issue by jotish** [eclipse/paho.mqtt.android#159]
Please fill out the form below before submitting, thank you!

- [x] Bug exists Release Version 1.1.0 (Java Repository Master Branch) org.eclipse.paho:org.eclipse.paho.android.service:1.1.0
- [ ] Bug exists in Snapshot Version 1.1.1-SNAPSHOT (Android Service Repository Master Branch)
- [ ] Bug is just in the Sample Application.

__Android API Version Bug Seen on:__
Android v4.4.4
__Android Version Bug Seen on:__

Please also check that if you have found the bug in the Release version (1.1.0) that you check that it also exists in the Snapshot (1.1.1-SNAPSHOT) before raising a bug.

## Description of Bug:
E.g. Steps to re-create, how often does this happen etc..
Internet connection on/off

## Console Log output (if available):
```
Fatal Exception: java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x8000010 (has extras) } in org.eclipse.paho.android.service.MqttService$NetworkConnectionIntentReceiver@41c25c08
       at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:798)
       at android.os.Handler.handleCallback(Handler.java:800)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5370)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by java.lang.NullPointerException
       at org.eclipse.paho.android.service.MqttConnection.reconnect(MqttConnection.java:1064)
       at org.eclipse.paho.android.service.MqttService.reconnect(MqttService.java:343)
       at org.eclipse.paho.android.service.MqttService$NetworkConnectionIntentReceiver.onReceive(MqttService.java:826)
       at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:788)
       at android.os.Handler.handleCallback(Handler.java:800)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5370)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by miketran78727** [comment]
I believe this problem has been fixed in develop branch.  

Would you please try the snapshot build? https://repo.eclipse.org/content/repositories/paho-snapshots/org/eclipse/paho/
