### ISSUE TITLE
Crash on creating a logger for Chinese locale

### ISSUE THREAD

**Issue by baole** [eclipse/paho.mqtt.android#168]
Please fill out the form below before submitting, thank you!

- [ ] Bug exists Release Version 1.1.0 (Java Repository Master Branch)
- [ x ] Bug exists in Snapshot Version 1.1.1-SNAPSHOT (Android Service Repository Master Branch)
- [ ] Bug is just in the Sample Application.

__Android API Version Bug Seen on: API 16+

__Android Version Bug Seen on:

Please also check that if you have found the bug in the Release version (1.1.0) that you check that it also exists in the Snapshot (1.1.1-SNAPSHOT) before raising a bug.

## Description of Bug:
E.g. Steps to re-create, how often does this happen etc..

## Console Log output (if available):

Crashlytics: http://crashes.to/s/f231fde80f2

```
Fatal Exception: java.lang.ExceptionInInitializerError
       at org.eclipse.paho.android.service.MqttConnection.connect(Unknown Source:289)
       at org.eclipse.paho.android.service.MqttService.connect(Unknown Source:329)
       at org.eclipse.paho.android.service.MqttAndroidClient.doConnect(Unknown Source:469)
       at org.eclipse.paho.android.service.MqttAndroidClient.access$200(Unknown Source:76)
       at org.eclipse.paho.android.service.MqttAndroidClient$MyServiceConnection.onServiceConnected(Unknown Source:115)
       at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1247)
       at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1264)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5637)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
Caused by java.util.MissingResourceException: Can't find resource for bundle 'org.eclipse.paho.client.mqttv3.internal.nls.logcat_zh_CN', key ''
       at java.util.ResourceBundle.missingResourceException(ResourceBundle.java:238)
       at java.util.ResourceBundle.getBundle(ResourceBundle.java:230)
       at java.util.ResourceBundle.getBundle(ResourceBundle.java:139)
       at org.eclipse.paho.client.mqttv3.logging.LoggerFactory.getLogger(Unknown Source:72)
       at org.eclipse.paho.client.mqttv3.MqttAsyncClient.(Unknown Source:89)
       at org.eclipse.paho.android.service.MqttConnection.connect(Unknown Source:289)
       at org.eclipse.paho.android.service.MqttService.connect(Unknown Source:329)
       at org.eclipse.paho.android.service.MqttAndroidClient.doConnect(Unknown Source:469)
       at org.eclipse.paho.android.service.MqttAndroidClient.access$200(Unknown Source:76)
       at org.eclipse.paho.android.service.MqttAndroidClient$MyServiceConnection.onServiceConnected(Unknown Source:115)
       at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1247)
       at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1264)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5637)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)


```

**Comment by jpwsutton** [comment]
Currently the Logger messages are only in the default logcat.properties file, we do not have any that have been translated for Chinese I'm afraid.

**Comment by leexen** [comment]
Also meet the same problem.

**Comment by JNYoung** [comment]
Where use this property file, can I take this off?

**Comment by ainiyiwan** [comment]
@jpwsutton did you know how to save this problem ?

**Comment by Perter89757** [comment]
以前没有出现这个问题,这次崩溃的原因是:,生成aar的时候,删除mqttv3.internal.nls文件夹下面的logcat.properties导致的,

**Comment by godchengvip** [comment]
Try modifying packagingOptions in the build. gradle file
