### ISSUE TITLE
NullPointerException: Timer.cancel()

### ISSUE THREAD

**Issue by laichuangwen** [eclipse/paho.mqtt.android#180]
Bug exists Release Version 1.1.1
When the server didn't open ,switching network,crash
log:
 at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:924)
                                                                                  at android.os.Handler.handleCallback(Handler.java:815)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                                  at android.os.Looper.loop(Looper.java:194)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5546)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:967)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
                                                                               Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.util.Timer.cancel()' on a null object reference
                                                                                  at org.eclipse.paho.client.mqttv3.MqttAsyncClient.stopReconnectCycle(MqttAsyncClient.java:1120)
                                                                                  at org.eclipse.paho.client.mqttv3.MqttAsyncClient.reconnect(MqttAsyncClient.java:1057)
                                                                                  at org.eclipse.paho.android.service.MqttConnection.reconnect(MqttConnection.java:1049)
                                                                                  at org.eclipse.paho.android.service.MqttService.reconnect(MqttService.java:342)
                                                                                  at org.eclipse.paho.android.service.MqttService$NetworkConnectionIntentReceiver.onReceive(MqttService.java:827)
                                                                                  at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:914)
                                                                                  at android.os.Handler.handleCallback(Handler.java:815) 
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:104) 
                                                                                  at android.os.Looper.loop(Looper.java:194) 
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5546) 
                                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                                  at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:967) 
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)

**Comment by miketran78727** [comment]
This should be fixed when we have a fix for this Java client issue: https://github.com/eclipse/paho.mqtt.java/issues/325

**Comment by jpwsutton** [comment]
Should now be resolved by: https://github.com/eclipse/paho.mqtt.java/pull/326

**Comment by elsennov** [comment]
@jpwsutton When will this fix be on the released version? I got this error in production :(

**Comment by jflavio1** [comment]
@jpwsutton  @elsennov Same error here, this makes my app fails in Android :/

**Comment by jflavio1** [comment]
@elsennov setting on Build.gradle `org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.1.1-SNAPSHOT`
worked for me 👍

**Comment by elsennov** [comment]
Ah, thanks @jflavio1 will try asap

**Comment by rafaelekol** [comment]
Getting same exception, when will be next release to get this fix?

**Comment by dimparf** [comment]
Also getting same exception on reconnect after long network disabled period. paho.android 1.1.1 / Android 7.1

**Comment by jpwsutton** [comment]
What version of the Paho Java library are you including in your Gradle build file or maven pom?

**Comment by dimparf** [comment]
@jpwsutton Paho Java library 1.1.0 / paho.mqtt.android 1.1.1.

**Comment by jpwsutton** [comment]
@dimparf Right, the fix that is in the Java client has not been released and so is only available in the 1.1.1 snapshot: https://repo.eclipse.org/content/repositories/paho-snapshots/org/eclipse/paho/org.eclipse.paho.client.mqttv3/1.1.1-SNAPSHOT/

We are planning on doing a service release of the Java client soon though so it will be available as a full release after that.

**Comment by dimparf** [comment]
Ok, thanks.

**Comment by rafaelekol** [comment]
We are having many crashes on our production app, due to this issue, Can you make publish new release with this fix.

**Comment by jpwsutton** [comment]
The Java client has now had it's 1.1.1 service release and is available on both repo.eclipse.org and Maven Central. I recommend updating your dependency for the Java library to 1.1.1 and this issue should be resolved.

**Comment by dimparf** [comment]
@jpwsutton Thanks, now paho android client is very stable!
