### ISSUE TITLE
NPE on publish

### ISSUE THREAD

**Issue by ByTE1974** [eclipse/paho.mqtt.android#183]
- [x] Bug exists Release Version 1.1.1 (Java Repository Master Branch)
I my gradle I have:
```compile 'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.1.1-SNAPSHOT'```
```compile 'org.eclipse.paho:org.eclipse.paho.android.service:1.1.1'```

__Android Version Bug Seen on:__
4.4.2

## Description of Bug:
Appeared only twice among 10000 installations.
I personally can't reproduce it. I have received crash reports via Fabric. I don't have more information.

## Console Log output (if available):
```Fatal Exception: java.lang.NullPointerException```
```       at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:883)```
```       at org.eclipse.paho.android.service.MqttService.getConnection(MqttService.java:586)```
```       at org.eclipse.paho.android.service.MqttService.publish(MqttService.java:442)```
```       at org.eclipse.paho.android.service.MqttAndroidClient.publish(MqttAndroidClient.java:720)```
```       at org.eclipse.paho.android.service.MqttAndroidClient.publish(MqttAndroidClient.java:647)```

**Comment by jpwsutton** [comment]
Hmm, looks like the client is attempting to publish after the MqttService is no longer available and is null. This could be related to Issue #99, #84 and #8

**Comment by rafaelekol** [comment]
Observe same issue on Samsung S6 Edge, Android 6. Is there a way to reconnect the client on this type of error.

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Object.hashCode()' on a null object reference
                                             at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:772)
                                             at org.eclipse.paho.android.service.MqttService.getConnection(MqttService.java:586)
                                             at org.eclipse.paho.android.service.MqttService.publish(MqttService.java:467)
                                             at org.eclipse.paho.android.service.MqttAndroidClient.publish(MqttAndroidClient.java:815)
                                             at org.eclipse.paho.android.service.MqttAndroidClient.publish(MqttAndroidClient.java:673)
                                             at com.example.app.core.mqtt.MqttAppService.publishMessage(MqttAppService.java:309)
```

**Comment by jpwsutton** [comment]
Though It looks like the cause of the ConcurrentHashMap error was that the clientHandle was null when attempting to get the connection, PR #263 adds a null check which will return a more human readable error in this scenario. The Publish error is due to the fact that the MqttService is null at that point. Either because it has not yet been created or has become disconnected / unbound. I'm looking at another solution for this in particular, though it may also be more useful error messages at this point.

**Comment by plentz** [comment]
I seeing this quite frequently while calling `disconnect` on a `client` as well

```
06-15 16:53:37.026   737   989 W System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Object.hashCode()' on a null object reference
06-15 16:53:37.026   737   989 W System.err: 	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:746)
06-15 16:53:37.026   737   989 W System.err: 	at org.eclipse.paho.android.service.MqttService.b(MqttService.java:586)
06-15 16:53:37.026   737   989 W System.err: 	at org.eclipse.paho.android.service.MqttService.a(MqttService.java:370)
06-15 16:53:37.026   737   989 W System.err: 	at org.eclipse.paho.android.service.d.c(MqttAndroidClient.java:498)
```

**Comment by Raja-Raman** [comment]
I observe this crash consistently in Android SDK 26, as on July 2018:
 
MqttAndroidClient client;
client(connect();
// do stuff
client.disconnect();
if (client==null)
    return;
if (client.isConnected()) {  /* crashes here */   
// do stuff
} 

The error message is:
Attempt to invoke virtual method 'int java.lang.Object.hashCode()' on a null object reference.

Please suggest any work around.
