### ISSUE TITLE
Does not reconnect throwing BufferQueue Error

### ISSUE THREAD

**Issue by wajidp** [eclipse/paho.mqtt.android#194]
Does not reconnect to mqtt server throws Buffer Queue error

03-26 17:32:23.690 2508-12844 E/BufferQueue: [dt.mcwcs.dtc/dt.mcwcs.activity.DTCDashboardActivity] dequeueBuffer: can't dequeue multiple buffers without setting the buffer count
03-26 17:32:23.710 6809-6809 W/System.err: Client is connected (32100)
03-26 17:32:23.710 6809-6809 W/System.err:     at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:31)
03-26 17:32:23.710 6809-6809 W/System.err:     at org.eclipse.paho.client.mqttv3.MqttAsyncClient.connect(MqttAsyncClient.java:530)
03-26 17:32:23.710 6809-6809 W/System.err:     at org.eclipse.paho.android.service.MqttConnection.connect(MqttConnection.java:283)
03-26 17:32:23.710 6809-6809 W/System.err:     at org.eclipse.paho.android.service.MqttService.connect(MqttService.java:330)
03-26 17:32:23.710 6809-6809 W/System.err:     at org.eclipse.paho.android.service.MqttAndroidClient.doConnect(MqttAndroidClient.java:474)
03-26 17:32:23.710 6809-6809 W/System.err:     at org.eclipse.paho.android.service.MqttAndroidClient.access$200(MqttAndroidClient.java:77)
03-26 17:32:23.710 6809-6809 W/System.err:     at org.eclipse.paho.android.service.MqttAndroidClient$MyServiceConnection.onServiceConnected(MqttAndroidClient.java:116)
03-26 17:32:23.710 6809-6809 W/System.err:     at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1106)
03-26 17:32:23.710 6809-6809 W/System.err:     at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1123)
03-26 17:32:23.710 6809-6809 W/System.err:     at android.os.Handler.handleCallback(Handler.java:730)
03-26 17:32:23.710 6809-6809 W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:92)
03-26 17:32:23.710 6809-6809 W/System.err:     at android.os.Looper.loop(Looper.java:137)
03-26 17:32:23.710 6809-6809 W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5103)
03-26 17:32:23.710 6809-6809 W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
03-26 17:32:23.710 6809-6809 W/System.err:     at java.lang.reflect.Method.invoke(Method.java:525)
03-26 17:32:23.710 6809-6809 W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
03-26 17:32:23.710 6809-6809 W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
03-26 17:32:23.710 6809-6809 W/System.err:     at dalvik.system.NativeStart.main(Native Method)

**Comment by jpwsutton** [comment]
The Buffer Queue error does not come from the Paho Service, so you will need to look into that separately. But by the looks of it, the Paho exception that is being thrown is due to the fact that the client is already connected and so does not need to Reconnect.

**Comment by wajidp** [comment]
The server where the broker was hosted was affected with a power failure and went for a restart, after the incident am getting above exception when i try to reconnect. If i clear from the recents and try it works.
