### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by zhanghao813207** [eclipse/paho.mqtt.android#199]
hi,I have a problem with this version。
- [ ] Mqttv3 Snapshot Version 1.1.1-SNAPSHOT
- [ ] Service Snapshot Version 1.1.2-SNAPSHOT (Android Service Repository Master Branch)

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.eclipse.paho.android.service.MqttService.traceError(java.lang.String, java.lang.String)' on a null object reference
       at org.eclipse.paho.android.service.MqttAndroidClient.messageArrivedAction(MqttAndroidClient.java:1517)
       at org.eclipse.paho.android.service.MqttAndroidClient.onReceive(MqttAndroidClient.java:1307)
       at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:297)
       at android.support.v4.content.LocalBroadcastManager.access$000(LocalBroadcastManager.java:46)
       at android.support.v4.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:116)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:199)
       at android.app.ActivityThread.main(ActivityThread.java:5848)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1003)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:798)

**Comment by khannasaransh** [comment]
I am having the same issue with 
compile 'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.0'
compile 'org.eclipse.paho:org.eclipse.paho.android.service:1.1.1'
