### ISSUE TITLE
clientHandle null on disconnect

### ISSUE THREAD

**Issue by mckayb24** [eclipse/paho.mqtt.android#206]
- [x ] Bug exists Release Version 1.1.1 (Java Repository Master Branch)
- [x ] Bug exists in Snapshot Version 1.1.2-SNAPSHOT (Android Service Repository Master Branch)
- [ ] Bug is just in the Sample Application.

__Android API Version Bug Seen on:__
        minSdkVersion 18
        targetSdkVersion 25
__Android Version Bug Seen on:__
device: 5.0

## Description of Bug:
E.g. Steps to re-create, how often does this happen etc..
I connect to the mqttClient in onCreate and disconnect in onDestroy.

If I rotate the screen twice in quick succession the null pointer exception below is thrown.
I think the issue happens because the connection has not been established so the clientHandle is still null.
## Console Log output:
04-25 12:18:24.442 5365-5365/geotrac.android.apps.mocom E/AndroidRuntime: FATAL EXCEPTION: main
                                                                          Process: geotrac.android.apps.mocom, PID: 5365
                                                                          java.lang.RuntimeException: Unable to stop service geotrac.android.apps.mocom.GpaService@207cc979: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Object.hashCode()' on a null object reference
                                                                              at android.app.ActivityThread.handleStopService(ActivityThread.java:2911)
                                                                              at android.app.ActivityThread.access$2200(ActivityThread.java:144)
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1381)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                              at android.os.Looper.loop(Looper.java:135)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5221)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at java.lang.reflect.Method.invoke(Method.java:372)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
                                                                           Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Object.hashCode()' on a null object reference
                                                                              at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:746)
                                                                              at org.eclipse.paho.android.service.MqttService.getConnection(MqttService.java:580)
                                                                              at org.eclipse.paho.android.service.MqttService.disconnect(MqttService.java:370)
                                                                              at org.eclipse.paho.android.service.MqttAndroidClient.disconnect(MqttAndroidClient.java:486)
                                                                              at geotrac.android.apps.mocom.common.ParsedDataMqttClient.disconnect(ParsedDataMqttClient.java:75)
                                                                              at geotrac.android.apps.mocom.GpaService.onDestroy(GpaService.java:136)
                                                                              at android.app.ActivityThread.handleStopService(ActivityThread.java:2894)
                                                                              at android.app.ActivityThread.access$2200(ActivityThread.java:144) 
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1381) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                              at android.os.Looper.loop(Looper.java:135) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5221) 
                                                                              at java.lang.reflect.Method.invoke(Native Method) 
                                                                              at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899) 
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by jpwsutton** [comment]
I've added a null check on the clientHandle in PR #263 which will return a better error message, Usually the best practice is to wait for the connected callback to return before making further calls to the API, however that isn't quite ideal either.

**Comment by tejas-n** [comment]
@jpwsutton  Does that mean that `MqttAndroidClient` never attempts to cancel an ongoing connection operation even after you've called `disconnect()` ? It seems a little inconvenient to wait for the connection to be established in order to call `disconnect()`.
