### ISSUE TITLE
javax.net.ssl.SSLException

### ISSUE THREAD

**Issue by armen301** [eclipse/paho.mqtt.android#217]
Please fill out the form below before submitting, thank you!

- [ ] Bug exists Release Version 1.1.1 (Java Repository Master Branch)
- [ ] Bug exists in Snapshot Version 1.1.2-SNAPSHOT (Android Service Repository Master Branch)
- [ ] Bug is just in the Sample Application.

__Android API Version Bug Seen on:__

__Android Version Bug Seen on:__

Please also check that if you have found the bug in the Release version (1.1.1) that you check that it also exists in the Snapshot (1.1.2-SNAPSHOT) before raising a bug.

## Description of Bug:
E.g. Steps to re-create, how often does this happen etc..

## Console Log output (if available):
```
javax.net.ssl.SSLException: Read error: ssl=0x555cfec070: I/O error during system call, Connection reset by peer
	at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
	at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:699)
	at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:672)
	at java.io.DataInputStream.readByte(DataInputStream.java:75)
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:65)
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:107)
	at java.lang.Thread.run(Thread.java:818)
```

**Comment by Zugreiter** [comment]
Hey,

i can confirm this bug. In our app it appears many times a day. There might be a side effect with the reconnection feature of the MqttAndroidClient. We discovered a **massive delay while reconnecting** to the broker. The second log displays a delay of over an hour until the reconnection occurs. But there was no reason for this because the phone (Nexus 5X) had always a good connection to the wifi and was not moved to another location in this time.

## Build Gradle (app-level)
```
    compile 'org.eclipse.paho:org.eclipse.paho.android.service:1.1.1'
    compile 'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.1.1' 
```

## Mqtt Client Setup

```java
class MqttService extends Service
{
    private static final String USER = "user";
    private static final String PASSWORD = "password";
    private static final String SERVER_URL_WITH_SSL = "ssl://my-mqtt-broker:8883";

    @Getter
    protected MqttAndroidClient mqttAndroidClient;

    @Override
    public void onCreate()
    {
        super.onCreate();

	this.mqttAndroidClient = this.createMqttClient(SERVER_URL_WITH_SSL)
		
        SSLSocketFactory sslSocketFactory = this.createSSLSocketFactory();

        this.connectToMqttBroker(this.mqttAndroidClient, this.sslSocketFactory);
    }

    public IMqttDeliveryToken publish(String topic, MqttMessage mqttMessage, Object context)
    {
        try
        {
            return this.mqttAndroidClient.publish(topic, mqttMessage, context, null);
        }
        catch (MqttException e)
        {
            LOG.error("An error occurred during publishing an MqttMessage to topic: " + topic, e);
            return null;
        }
    }

    protected void subscribeToTopic(String topic)
    {
        try
        {
            this.mqttAndroidClient.subscribe(topic, 1, null, new LoggingMqttListener());
        }
        catch (MqttException ex)
        {
            LOG.error("Exception while subscribing", ex);
        }
    }

    protected void subscribeToTopic(String topic, boolean reconnect)
    {
        if (reconnect) subscribeToTopic(topic);
    }

    private void connectToMqttBroker(MqttAndroidClient mqttClient, SSLSocketFactory sslSocketFactory)
    {
        MqttConnectOptions mqttConnectOptions = new MqttConnectOptions();
        mqttConnectOptions.setAutomaticReconnect(true);
        mqttConnectOptions.setCleanSession(false);
        mqttConnectOptions.setUserName(USER);
        mqttConnectOptions.setPassword(PASSWORD.toCharArray());
	mqttConnectOptions.setSocketFactory(sslSocketFactory);

        try
        {
            mqttClient.connect(mqttConnectOptions, null, new IMqttActionListener()
            {
                @Override
                public void onSuccess(IMqttToken asyncActionToken)
                {
                    DisconnectedBufferOptions disconnectedBufferOptions = new DisconnectedBufferOptions();
                    disconnectedBufferOptions.setBufferEnabled(true);
                    disconnectedBufferOptions.setBufferSize(100);
                    disconnectedBufferOptions.setPersistBuffer(false);
                    disconnectedBufferOptions.setDeleteOldestMessages(false);
                    mqttAndroidClient.setBufferOpts(disconnectedBufferOptions);

                    subscribeToTopic(topic);
                }

                @Override
                public void onFailure(IMqttToken asyncActionToken, Throwable exception)
                {
                    LOG.debug("Failed to connectToMqttBroker to: " + SERVER_URL_WITH_SSL);
                }
            });
        }
        catch (MqttException ex)
        {
            LOG.error("Exception while connecting to mqtt broker", ex);
        }
    }

    private MqttAndroidClient createMqttClient(String serverUrl)
    {
        MqttAndroidClient mqttAndroidClient = new MqttAndroidClient(getApplicationContext(), serverUrl, clientId);

        mqttAndroidClient.setCallback(this.mqttCallback);
        mqttAndroidClient.setTraceEnabled(true);
        mqttAndroidClient.setTraceCallback(new PahoMqttTracer());

        return mqttAndroidClient;
    }

    private SSLSocketFactory createSSLSocketFactory()
    {
        try
        {
            CertificateFactory caCF = CertificateFactory.getInstance("X.509");
            X509Certificate ca = (X509Certificate) caCF.generateCertificate(this.getAssets().open("ca.crt"));

            KeyStore caKeyStore = KeyStore.getInstance(KeyStore.getDefaultType());
            caKeyStore.load(null, null);
            caKeyStore.setCertificateEntry(ca.getSubjectX500Principal().getName(), ca);

            TrustManagerFactory tmf = TrustManagerFactory.getInstance(TrustManagerFactory.getDefaultAlgorithm());
            tmf.init(caKeyStore);

            SSLContext context = SSLContext.getInstance("TLS");
            context.init(null, tmf.getTrustManagers(), null);
            return context.getSocketFactory();
        }
        catch (IOException | KeyStoreException | KeyManagementException | NoSuchAlgorithmException | CertificateException e)
        {
            LOG.error("Creating ssl socket factory failed", e);
            return null;
        }
    }
}
```

## Logs
```
10:41:51.930 [main] DEBUG d.s.services.PahoMqttTracer - MqttConnection: connectionLost(Connection lost)
10:41:51.936 [main] WARN  d.s.services.MqttService - Connection lost!
org.eclipse.paho.client.mqttv3.MqttException: Connection lost
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:164) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:761) ~[na:0.0]
Caused by: javax.net.ssl.SSLException: Read error: ssl=0x765b5f6380: I/O error during system call, Software caused connection abort
	at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method) ~[na:0.0]
	at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:758) ~[na:0.0]
	at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:731) ~[na:0.0]
	at java.io.DataInputStream.readByte(DataInputStream.java:268) ~[na:0.0]
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92) ~[na:0.0]
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:116) ~[na:0.0]
	... 1 common frames omitted
11:54:26.359 [main] DEBUG d.s.services.MqttService - Connection established to ssl://my-mqtt-broker.org:8883! Reconnect: true
11:54:26.360 [main] DEBUG d.s.services.MqttService - Try to subscribe to topic: mytopic
11:54:26.360 [main] DEBUG d.s.services.PahoMqttTracer - MqttConnection: subscribe({mytopic},1,{null}, {13}
11:54:26.398 [main] DEBUG d.s.services.MqttService - Subscribed
11:54:53.174 [main] DEBUG d.s.services.PahoMqttTracer - MqttConnection: connectionLost(Connection lost)
11:54:53.181 [main] WARN  d.s.services.MqttService - Connection lost!
org.eclipse.paho.client.mqttv3.MqttException: Connection lost
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:164) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:761) ~[na:0.0]
Caused by: javax.net.ssl.SSLException: Read error: ssl=0x765b5f6380: I/O error during system call, Software caused connection abort
	at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method) ~[na:0.0]
	at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:758) ~[na:0.0]
	at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:731) ~[na:0.0]
	at java.io.DataInputStream.readByte(DataInputStream.java:268) ~[na:0.0]
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92) ~[na:0.0]
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:116) ~[na:0.0]
	... 1 common frames omitted
12:09:07.525 [main] DEBUG d.s.services.MqttService - Connection established to ssl://my-mqtt-broker.org:8883! Reconnect: true
12:09:07.526 [main] DEBUG d.s.services.MqttService - Try to subscribe to topic: mytopic
12:09:07.527 [main] DEBUG d.s.services.PahoMqttTracer - MqttConnection: subscribe({mytopic},1,{null}, {14}
12:09:07.606 [main] DEBUG d.s.services.MqttService - Subscribed
```
Log with massive delay
```
15:18:52.550 [main] DEBUG d.s.services.PahoMqttTracer - MqttConnection: connectionLost(Connection lost)
15:18:52.557 [main] WARN  d.s.services.MqttService - Connection lost!
org.eclipse.paho.client.mqttv3.MqttException: Connection lost
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:164) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:761) ~[na:0.0]
Caused by: javax.net.ssl.SSLException: Read error: ssl=0x765b5f92c0: I/O error during system call, Software caused connection abort
	at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method) ~[na:0.0]
	at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:758) ~[na:0.0]
	at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:731) ~[na:0.0]
	at java.io.DataInputStream.readByte(DataInputStream.java:268) ~[na:0.0]
	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92) ~[na:0.0]
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:116) ~[na:0.0]
	... 1 common frames omitted
16:46:36.899 [main] DEBUG d.s.services.MqttService - Connection established to ssl://my-mqtt-broker.org:8883! Reconnect: true
16:46:36.907 [main] DEBUG d.s.services.MqttService - Try to subscribe to topic: mytopic
16:46:36.910 [main] DEBUG d.s.services.PahoMqttTracer - MqttConnection: subscribe({mytopic},1,{null}, {3}
16:46:37.070 [main] DEBUG d.s.services.MqttService - Subscribed
```

**Comment by nguyenlinhnttu** [comment]
Please  follow this link, I have connected with websocket wss://xxx 

https://transoceanic.blogspot.com/2011/11/android-import-ssl-certificate-and-use.html
