### ISSUE TITLE
Timer.cancel throwing exception

### ISSUE THREAD

**Issue by pavan2you** [eclipse/paho.mqtt.android#220]
Please fill out the form below before submitting, thank you!

- [ √] Bug exists Release Version 1.1.1 (Java Repository Master Branch)
- [√ ] Bug exists in Snapshot Version 1.1.2-SNAPSHOT (Android Service Repository Master Branch)
- [ ] Bug is just in the Sample Application.

__Android API Version Bug Seen on:__
15 onwards
__Android Version Bug Seen on:__
from 4.0.x onwards

Please also check that if you have found the bug in the Release version (1.1.1) that you check that it also exists in the Snapshot (1.1.2-SNAPSHOT) before raising a bug.

## Description of Bug:
E.g. Steps to re-create, how often does this happen etc..
Randomly happening. But frequency is very high

## Console Log output (if available):
Fatal Exception: java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4000010 (has extras) } in org.eclipse.paho.android.service.MqttService$NetworkConnectionIntentReceiver@c8951e6
       at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1132)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6121)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
Caused by java.lang.IllegalStateException: Timer already cancelled.
       at java.util.Timer.sched(Timer.java:397)
       at java.util.Timer.schedule(Timer.java:193)
       at org.eclipse.paho.client.mqttv3.MqttAsyncClient.rescheduleReconnectCycle(SourceFile:1129)
       at org.eclipse.paho.client.mqttv3.MqttAsyncClient.access$8(SourceFile:1125)
       at org.eclipse.paho.client.mqttv3.MqttAsyncClient$2.onFailure(SourceFile:1093)
       at org.eclipse.paho.client.mqttv3.internal.ConnectActionListener.onFailure(SourceFile:161)
       at org.eclipse.paho.client.mqttv3.internal.ConnectActionListener.connect(SourceFile:189)
       at org.eclipse.paho.client.mqttv3.internal.ConnectActionListener.onFailure(SourceFile:138)
       at org.eclipse.paho.client.mqttv3.internal.ConnectActionListener.connect(SourceFile:189)
       at org.eclipse.paho.client.mqttv3.MqttAsyncClient.connect(SourceFile:592)
       at org.eclipse.paho.client.mqttv3.MqttAsyncClient.attemptReconnect(SourceFile:1078)
       at org.eclipse.paho.client.mqttv3.MqttAsyncClient.reconnect(SourceFile:1059)
       at org.eclipse.paho.android.service.MqttConnection.reconnect(SourceFile:1049)
       at org.eclipse.paho.android.service.MqttService.reconnect(SourceFile:369)
       at org.eclipse.paho.android.service.MqttService$NetworkConnectionIntentReceiver.onReceive(SourceFile:858)
       at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1122)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6121)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Comment by pavan2you** [comment]
Hi Can you please check this issue? it is very frequent and our production app is keep breaking because of this.

**Comment by yiyayiya** [comment]
compile 'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.1.1'

**Comment by yiyayiya** [comment]
compile 'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.1.1'

https://github.com/eclipse/paho.mqtt.java/blob/master/org.eclipse.paho.client.mqttv3/src/main/java/org/eclipse/paho/client/mqttv3/MqttAsyncClient.java

```
private void stopReconnectCycle(){
--
  | String methodName = "stopReconnectCycle";
  | //@Trace 504=Stop reconnect timer for client: {0}
  | log.fine(CLASS_NAME, methodName, "504", new Object[]{this.clientId});
  | synchronized(clientLock) {
  | if (this.connOpts.isAutomaticReconnect()) {
  | if(reconnectTimer != null){
  | reconnectTimer.cancel();
  | reconnectTimer = null;
  | }
  | reconnectDelay = 1000; // Reset Delay Timer
  | }
  | }
  | }
  |  
  | private void rescheduleReconnectCycle(int delay){
  | String methodName = "rescheduleReconnectCycle";
  | //@Trace 505=Rescheduling reconnect timer for client: {0}, delay: {1}
  | log.fine(CLASS_NAME, methodName, "505", new Object[]{this.clientId, new Long(reconnectDelay)});
  | synchronized(clientLock) {
  | if(this.connOpts.isAutomaticReconnect()) {
  | if (reconnectTimer != null) {
  | reconnectTimer.schedule(new ReconnectTask(), delay);
  | } else {
  | // The previous reconnect timer was cancelled
  | reconnectDelay = delay;
  | startReconnectCycle();
  | }
  | }
  | }
  | }
  |  
```

**Comment by pavan2you** [comment]
Hi yiyayiya,

I made a fix like below

private void rescheduleReconnectCycle(int delay){
		String methodName = "rescheduleReconnectCycle";
		//@Trace 505=Rescheduling reconnect timer for client: {0}, delay: {1}
		log.fine(CLASS_NAME, methodName, "505", new Object[]{this.clientId, new Long(reconnectDelay)});
		synchronized(clientLock) {
			if(this.connOpts.isAutomaticReconnect()) {
				if (reconnectTimer != null) {
					try {
					reconnectTimer.schedule(new ReconnectTask(), delay);
					} catch(IllegalStateException e) {
						e.printStackTrace();
						
						// The previous reconnect timer state is illegal
						reconnectDelay = delay;
						startReconnectCycle();
					}
				} else {
					// The previous reconnect timer was cancelled
					reconnectDelay = delay;
					startReconnectCycle();
				}
			}
		}
	}

**Comment by woitaylor** [comment]
//mqtt
    implementation 'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.5'
    implementation 'org.eclipse.paho:org.eclipse.paho.android.service:1.1.1'
