### ISSUE TITLE
Exception on network change sometime reconnect

### ISSUE THREAD

**Issue by shainsingh89** [eclipse/paho.mqtt.android#224]
Please fill out the form below before submitting, thank you!

- [* ] Bug exists Release Version 1.1.1 (Java Repository Master Branch)

__Android API Version Bug Seen on:__ 3.1.1

__Android Version Bug Seen on:__  26

Please also check that if you have found the bug in the Release version (1.1.1) that you check that it also exists in the Snapshot (1.1.2-SNAPSHOT) before raising a bug.

## Description of Bug:
When mqtt server in connected and try to switch network or 
Disconnecting and connecting the network
**on mqtt.reconnect() 
    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.util.Timer.cancel()' on a null object reference**

## Console Log output (if available):

`java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4000010 (has extras) } in org.eclipse.paho.android.service.MqttService$NetworkConnectionIntentReceiver@905c256
                                                                              at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1132)
                                                                              at android.os.Handler.handleCallback(Handler.java:751)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                              at android.os.Looper.loop(Looper.java:154)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:6121)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
                                                                           Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.util.Timer.cancel()' on a null object reference
                                                                              at org.eclipse.paho.client.mqttv3.MqttAsyncClient.stopReconnectCycle(MqttAsyncClient.java:1120)
                                                                              at org.eclipse.paho.client.mqttv3.MqttAsyncClient.reconnect(MqttAsyncClient.java:1057)
                                                                              at org.eclipse.paho.android.service.MqttConnection.reconnect(MqttConnection.java:1049)
                                                                              at org.eclipse.paho.android.service.MqttService.reconnect(MqttService.java:342)
                                                                              at org.eclipse.paho.android.service.MqttService$NetworkConnectionIntentReceiver.onReceive(MqttService.java:827)
                                                                              at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1122)
                                                                              at android.os.Handler.handleCallback(Handler.java:751) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                              at android.os.Looper.loop(Looper.java:154) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:6121) 
                                                                              at java.lang.reflect.Method.invoke(Native Method) 
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889) 
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779) `

**Comment by pauldanckaert** [comment]
I absolutely have this issue as well, and it's pretty easy to reproduce. Take a cell phone, for example, and connect while on wifi, then turn off wifi and switch to cellular. It will crash pretty consistently.

**Comment by SardarKhan299** [comment]
I am also experience the same issue kindly solve it soon thanks here is the stack trace

Fatal Exception: java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4000010 (has extras) } in org.eclipse.paho.android.service.MqttService$NetworkConnectionIntentReceiver@d08950d
at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:974)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:179)
at android.app.ActivityThread.main(ActivityThread.java:5730)
at java.lang.reflect.Method.invoke(Method.java)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:791)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:681)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'void java.util.Timer.cancel()' on a null object reference
at org.eclipse.paho.client.mqttv3.MqttAsyncClient.stopReconnectCycle(MqttAsyncClient.java:1120)
at org.eclipse.paho.client.mqttv3.MqttAsyncClient.reconnect(MqttAsyncClient.java:1057)
at org.eclipse.paho.android.service.MqttConnection.reconnect(MqttConnection.java:1049)
at org.eclipse.paho.android.service.MqttService.reconnect(MqttService.java:342)
at org.eclipse.paho.android.service.MqttService$NetworkConnectionIntentReceiver.onReceive(MqttService.java:827)
at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:957)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:179)
at android.app.ActivityThread.main(ActivityThread.java:5730)
at java.lang.reflect.Method.invoke(Method.java)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:791)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:681)

**Comment by pauldanckaert** [comment]
This is a pretty critical issue for me as well.

**Comment by SardarKhan299** [comment]
Kindly Solve this issue as we are experience alot of crashes due to this issue.thanks

**Comment by kmcheung12** [comment]
Same issue here

It is due to `MqttAsyncClient.java` 

```
	private void stopReconnectCycle(){
		String methodName = "stopReconnectCycle";
		//@Trace 504=Stop reconnect timer for client: {0}
		log.fine(CLASS_NAME, methodName, "504", new Object[]{this.clientId});
		reconnectTimer.cancel();
		reconnectDelay = 1000; // Reset Delay Timer
		
	}
```

where `reconnectTimer` being null

**Comment by mohakapt** [comment]
It's happening to me too, causing my app to crash constantly.
