### ISSUE TITLE
Duplicate entry: android/support/compat/R.class

### ISSUE THREAD

**Issue by nguyenlinhnttu** [eclipse/paho.mqtt.android#242]
Please fill out the form below before submitting, thank you!

- [ ] Bug exists in Snapshot Version 1.1.2-SNAPSHOT (Android Service Repository Master Branch)

Please also check that if you have found the bug in the Release version (1.1.1) that you check that it also exists in the Snapshot (1.1.2-SNAPSHOT) before raising a bug.

## Description of Bug:
- In Android Studio 2.3.3, I can debug app with real phone.
- But when build to .apk
- I receive notify error, i search any but can't resovel it.
## Console Log output (if available):
Error:Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: android/support/compat/R.class

Please check image i find:
![image](https://user-images.githubusercontent.com/22162670/30251721-e3a0849c-968f-11e7-91f4-e48dd170e287.png)

**Comment by jotish** [comment]
Same for me. 

I had tried excluding it but still the issue persists. Any quick fixes? 😢 

```
    compile ('org.eclipse.paho:org.eclipse.paho.android.service:1.1.2-SNAPSHOT') {
        exclude group: 'com.android.support', module:'appcompat'
    }

```

**Comment by nguyenlinhnttu** [comment]
@jotish Current you can change to old version, and wait new version fix it.

**Comment by jotish** [comment]
@nguyenlinhnttu You mean 1.1.1-SNAPSHOT or 1.1.1   (release) ? 

There are some crashes in 1.1.2-SNAPSHOT so we were using it.

**Comment by nguyenlinhnttu** [comment]
@jotish  
Currently  we using two lib, I haven't seen the error yet, you can try it.
--------------------
compile 'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.1-SNAPSHOT'
compile 'org.eclipse.paho:org.eclipse.paho.android.service:1.1.1'

**Comment by blundell** [comment]
you had your exclude wrong, it should be:

```
compile ('org.eclipse.paho:org.eclipse.paho.android.service:1.1.2-SNAPSHOT') {
        exclude group: 'com.android.support', module:'support-v4'
    }
```

see here: https://github.com/eclipse/paho.mqtt.android/blob/master/org.eclipse.paho.android.service/build.gradle#L40

**Comment by nguyenlinhnttu** [comment]
@blundell  Not working, cant sync project .

**Comment by blundell** [comment]
Do you have a github branch reproducing the problem? Happy to have a go at fixing it for you

**Comment by appde** [comment]
To reproduce the issue you need to clone and make some changes to the [develop branch](https://github.com/eclipse/paho.mqtt.android/tree/develop) paho.mqtt.android.example
1. Change the project's variable serviceVersion from `serviceVersion = '1.1.2-SNAPSHOT'` to `serviceVersion = '1.1.2-20170908.044047-5'` in _...paho.mqtt.android-develop\build.gradle_. At the moment `1.1.2-20170908.044047-5` is the latest version that can be successfully built.
2. Comment-out `api project(':org.eclipse.paho.android.service')` in dependencies section of _...paho.mqtt.android.example\build.gradle_ and uncomment two next lines:
- `api "org.eclipse.paho:org.eclipse.paho.client.mqttv3:${rootProject.ext.clientVersion}"`
- `api "org.eclipse.paho:org.eclipse.paho.android.service:${rootProject.ext.clientVersion}"`
3. Change - `api "org.eclipse.paho:org.eclipse.paho.android.service:${rootProject.ext.clientVersion}"` to `api "org.eclipse.paho:org.eclipse.paho.android.service:${rootProject.ext.serviceVersion}"`

All of the above changes should finally look like this:
```
clientVersion = '1.1.2-SNAPSHOT'
serviceVersion = '1.1.2-20170908.044047-5'
...
dependencies {
//    api project(':org.eclipse.paho.android.service')
    api "org.eclipse.paho:org.eclipse.paho.client.mqttv3:${rootProject.ext.clientVersion}"
    api "org.eclipse.paho:org.eclipse.paho.android.service:${rootProject.ext.serviceVersion}"
...
}
```
4. If you run `paho.mqtt.android.example` configuration for device having API under 21, you will see the following output:
```
Error:Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Landroid/support/compat/R;
Error:com.android.dex.DexException: Multiple dex files define Landroid/support/compat/R;
Error:	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:661)
Error:	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:616)
Error:	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:598)
Error:	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
Error:	at com.android.dx.merge.DexMerger.merge(DexMerger.java:198)
Error:	at com.android.builder.dexing.DexArchiveMergerCallable.call(DexArchiveMergerCallable.java:61)
Error:	at com.android.builder.dexing.DexArchiveMergerCallable.call(DexArchiveMergerCallable.java:36)
Error:	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
Error:	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
Error:	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
Error:	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
Error:	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error:Execution failed for task ':paho.mqtt.android.example:transformDexArchiveWithDexMergerForDebug'.
> com.android.build.api.transform.TransformException: com.android.dex.DexException: Multiple dex files define Landroid/support/compat/R;
```
I use API 19 and Android Studio 3.0.
The same `paho.mqtt.android.example` configuration is successfully run with API >= 21
