### ISSUE TITLE
Reconnect NullPointerException

### ISSUE THREAD

**Issue by a648077105** [eclipse/paho.mqtt.android#269]
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        Process: paho.mqtt.java.example, PID: 30824
                                                                        java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4000010 (has extras) } in org.eclipse.paho.android.service.MqttService$NetworkConnectionIntentReceiver@4228fd88
                                                                            at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:808)
                                                                            at android.os.Handler.handleCallback(Handler.java:808)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:103)
                                                                            at android.os.Looper.loop(Looper.java:193)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5368)
                                                                            at java.lang.reflect.Method.invokeNative(Native Method)
                                                                            at java.lang.reflect.Method.invoke(Method.java:515)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:828)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:644)
                                                                            at dalvik.system.NativeStart.main(Native Method)
                                                                         Caused by: java.lang.NullPointerException
                                                                            at org.eclipse.paho.client.mqttv3.MqttAsyncClient.stopReconnectCycle(MqttAsyncClient.java:1120)
                                                                            at org.eclipse.paho.client.mqttv3.MqttAsyncClient.reconnect(MqttAsyncClient.java:1057)
                                                                            at org.eclipse.paho.android.service.MqttConnection.reconnect(MqttConnection.java:1049)
                                                                            at org.eclipse.paho.android.service.MqttService.reconnect(MqttService.java:342)
                                                                            at org.eclipse.paho.android.service.MqttService$NetworkConnectionIntentReceiver.onReceive(MqttService.java:827)
                                                                            at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:798)
                                                                            at android.os.Handler.handleCallback(Handler.java:808) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:103) 
                                                                            at android.os.Looper.loop(Looper.java:193) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5368) 
                                                                            at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                            at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:828) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:644) 
                                                                            at dalvik.system.NativeStart.main(Native Method)

**Comment by a648077105** [comment]
Premise: wrong server address and network changes

**Comment by rajeshkanna777** [comment]
Hi a648077105
 Am aslo got same error which version are you using in mqttclient ?

**Comment by a648077105** [comment]
Hi rajeshkanna777
Thank you very much,I'll try it for a moment.

**Comment by a648077105** [comment]
@rajeshkanna777 
I've updated it to
compile 'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.0'
I've seen the source code, It did solve the previous problem,but it's still wrong now

LOG:

 java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4000010 (has extras) } in org.eclipse.paho.android.service.MqttService$NetworkConnectionIntentReceiver@42349d10
at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:808)
at android.os.Handler.handleCallback(Handler.java:808)
at android.os.Handler.dispatchMessage(Handler.java:103)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:5368)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:828)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:644)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
at org.eclipse.paho.android.service.MqttConnection.reconnect(MqttConnection.java:1064)
at org.eclipse.paho.android.service.MqttService.reconnect(MqttService.java:343)
at org.eclipse.paho.android.service.MqttService$NetworkConnectionIntentReceiver.onReceive(MqttService.java:826)
at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:798)
... 9 more

**Comment by rajeshkanna777** [comment]
Can you clean the build and do it again 

Could you send me the mqtt connection sample code

**Comment by a648077105** [comment]
@rajeshkanna777 
thank you very much!  it's worked !
my build-cache used compile 'org.eclipse.paho:org.eclipse.paho.android.service:1.1.0'
it cause the the problem
