### ISSUE TITLE
MqttException(0) when trying to connect

### ISSUE THREAD

**Issue by yusufonderd** [eclipse/paho.mqtt.android#272]
```
       val clientId = "myRandomClientId"
       val url = "wss://xxxxxxx.iot.us-east-1.amazonaws.com/mqtt?...."
       val client = MqttAndroidClient(this, url, clientId)
       val token = client.connect()
        token.actionCallback = object : IMqttActionListener {
                override fun onSuccess(asyncActionToken: IMqttToken) {
                    // We are connected
                }

                override fun onFailure(asyncActionToken: IMqttToken, exception: Throwable) {
                    exception.printStackTrace()
                }
            }
```

I'm getting MqttException (0) in logcat. 
> Detailed exception log : System.err: MqttException (0)
> W:     at org.eclipse.paho.client.mqttv3.persist.MqttDefaultFilePersistence.restoreBackups(MqttDefaultFilePersistence.java:276)
> W:     at org.eclipse.paho.client.mqttv3.persist.MqttDefaultFilePersistence.open(MqttDefaultFilePersistence.java:126)
> W:     at org.eclipse.paho.client.mqttv3.MqttAsyncClient.<init>(MqttAsyncClient.java:391)
> W:     at org.eclipse.paho.android.service.MqttConnection.connect(MqttConnection.java:289)
> W:     at org.eclipse.paho.android.service.MqttService.connect(MqttService.java:329)
> W:     at org.eclipse.paho.android.service.MqttAndroidClient.doConnect(MqttAndroidClient.java:467)
> W:     at org.eclipse.paho.android.service.MqttAndroidClient.access$200(MqttAndroidClient.java:76)
> W:     at org.eclipse.paho.android.service.MqttAndroidClient$MyServiceConnection.onServiceConnected(MqttAndroidClient.java:115)
> W:     at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1453)
> W:     at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1481)
> W:     at android.os.Handler.handleCallback(Handler.java:751)
> W:     at android.os.Handler.dispatchMessage(Handler.java:95)
> W:     at android.os.Looper.loop(Looper.java:154)
> W:     at android.app.ActivityThread.main(ActivityThread.java:6119)
> W:     at java.lang.reflect.Method.invoke(Native Method)
> W:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
> W:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
>

**Comment by algrid** [comment]
As a workaround I use memory persistence:
```java
mqttAndroidClient = new MqttAndroidClient(context, serverUri, clientId,
                new MemoryPersistence(), MqttAndroidClient.Ack.AUTO_ACK);
```
Messages can be lost when the app is killed but that's ok for me.

**Comment by yusufonderd** [comment]
Thank you it's worked.

**Comment by wajdan846** [comment]
had this problem on Huawei and LG phones, working great on others e.g Samsung

**Comment by adiaghakhalu** [comment]
Thanks

**Comment by quxin** [comment]
从Log找到对应exception的地方，看到
if (!dataDir.canWrite()) {
			throw new MqttPersistenceException();
		}
报错。可以想到给app加上    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>权限，就可以了。

**Comment by allofmex** [comment]
Any progress here? I experience the same issue on Android 4.4 (with and without sd card). It works with MemoryPersistence, but not with MqttDefaultFilePersistence.
The proplem is at [MqttConnection.java#L225](https://github.com/eclipse/paho.mqtt.android/blob/b5d5e5ef91e846d39a365b8c561fa9670d34f691/org.eclipse.paho.android.service/src/main/java/org/eclipse/paho/android/service/MqttConnection.java#L225), seems no storage location can be found.
