### ISSUE TITLE
Attempt to invoke virtual method 'void java.lang.Thread.join()

### ISSUE THREAD

**Issue by rajeshkanna777** [eclipse/paho.mqtt.android#275]
Please fill out the form below before submitting, thank you!

- [ ] Bug exists Release Version 1.1.1 (Java Repository Master Branch)
- [ ] Bug exists in Snapshot Version 1.2.0 (Android Service Repository Master Branch)
- [ ] Bug is just in the Sample Application.

__Android API Version Bug Seen on:__

__Android Version Bug Seen on:__

Please also check that if you have found the bug in the Release version (1.1.1) that you check that it also exists in the Snapshot (1.1.2-SNAPSHOT) before raising a bug.

## Description of Bug:
E.g. Steps to re-create, how often does this happen etc..

## Console Log output (if available):
java.lang.NullPointerException: Attempt to invoke virtual method 'void java.lang.Thread.join()' on a null object reference
	at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketReceiver.stop(WebSocketReceiver.java:85)
	at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketReceiver.run(WebSocketReceiver.java:120)
	at java.lang.Thread.run(Thread.java:762)

**Comment by atthapon-k** [comment]
Any update about this?

**Comment by systane** [comment]
I am getting the error

**Comment by darylsze** [comment]
getting same error. Any updates?
