### ISSUE TITLE
Disconnect on device start

### ISSUE THREAD

**Issue by antoniovlasic** [eclipse/paho.mqtt.android#279]
When I just start my device I lose the connection twice and get it back. (Keep Alive 10s)

**Comment by antoniovlasic** [comment]
Maybe this helps:

01-14 22:53:41.747 3881-3881/com.xy.xyW/System.err:     at java.io.DataInputStream.readByte(DataInputStream.java:267)
01-14 22:53:41.747 3881-3881/com..xy.xy W/System.err:     at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:65)
01-14 22:53:41.747 3881-3881/com..xy.xy W/System.err:     at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:107)
01-14 22:53:41.748 3881-3881/com..xy.xy W/System.err:     at java.lang.Thread.run(Thread.java:762)

**Comment by antoniovlasic** [comment]
With a KAT of 30s it does not happen. The problem is I have to set it to 10s.

**Comment by antoniovlasic** [comment]
I found a solution by occasionally publishing a message to any topic. I guess that's a solution because the keep alive interval is never passed. So I guess on a device start the ping does not work instantly. Any solution? 

(BTW: Happens in 1.1.1, 1.1.2 not tested)
