### ISSUE TITLE
Crash after wifi disconnected and reconnected 

### ISSUE THREAD

**Issue by v2kb2l** [eclipse/paho.mqtt.android#300]
Please fill out the form below before submitting, thank you!

- [ ] Bug exists Release Version 1.1.1 (Java Repository Master Branch)
org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.1.0'
 'org.eclipse.paho:org.eclipse.paho.android.service:1.1.1'
- [ ] Bug exists in Snapshot Version 1.1.2-SNAPSHOT (Android Service Repository Master Branch)
- [ ] Bug is just in the Sample Application.

__Android API Version Bug Seen on:__
   Android 7.0
__Android Version Bug Seen on:__

Please also check that if you have found the bug in the Release version (1.1.1) that you check that it also exists in the Snapshot (1.1.2-SNAPSHOT) before raising a bug.
No available integrated.

## Description of Bug:
E.g. Steps to re-create, how often does this happen etc..
Switch off wifi and switch on.

## Console Log output (if available):
java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4000010 (has extras) } in org.eclipse.paho.android.service.MqttService$NetworkConnectionIntentReceiver@1486817
        at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1132)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6123)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.util.Timer.cancel()' on a null object reference
        at org.eclipse.paho.client.mqttv3.MqttAsyncClient.stopReconnectCycle(MqttAsyncClient.java:1120)
        at org.eclipse.paho.client.mqttv3.MqttAsyncClient.reconnect(MqttAsyncClient.java:1057)
        at org.eclipse.paho.android.service.MqttConnection.reconnect(MqttConnection.java:1049)
        at org.eclipse.paho.android.service.MqttService.reconnect(MqttService.java:342)
        at org.eclipse.paho.android.service.MqttService$NetworkConnectionIntentReceiver.onReceive(MqttService.java:827)
        at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1122)
        at android.os.Handler.handleCallback(Handler.java:751) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6123) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757) 
04-07 20:12:02.758 15847-15856/com.ctrlnode E/PowerManager: WakeLock finalized while still held: MQTT

**Comment by paulapithon** [comment]
I've encountered the same issue. The variable `reconnectTimer` on the `MqttAsyncClient` class is lacking a verification when it's called on the `stopReconnectCycle` method to check if it's null.

**Comment by paulapithon** [comment]
On #269 I saw I was supposed to change the gradle version and it works! Just please make sure the new version is specificated on paho's `read.me`.
