### ISSUE TITLE
Mqtt keeps disconnecting and reconnecting and not receive message from other devices

### ISSUE THREAD

**Issue by KonradSzewczuk** [eclipse/paho.mqtt.android#302]
On the bottom i provided sample log output which print like every seconds.

- [ ] Bug exists Release Version 1.1.1 (Java Repository Master Branch)

__Android API Version Bug Seen on:__
Samsung  Galaxy S6 API 23
Motorola XT1068 API 23
Meizu M3 Note

## Description of Bug:
When i publish event from one device to the broker my other device is not seeing the result.
The main bug is that mqtt client keep disconnecting and reconnecting(see the console log output) like every second or so.

Here is my Mqtt main configuration:

https://gist.github.com/KonradSzewczuk/6246967bb84c1cce4ba3ab5c15b9a324

## Console Log output (if available):
`04-18 16:45:53.029 12076-28666/com.myapp.tmt.app.verifier D/AlarmPingSender: Register alarmreceiver to MqttServiceMqttService.pingSender.13cab607-c94d-46d8-ae7f-ad889d16588f
04-18 16:45:53.039 12076-12076/com.myapp.tmt.app.verifier D/MqttHelper$initializeMq: Completed connection to: tcp://demo.ticketing.myapp.com:9393| Reconnect: true
04-18 16:45:54.249 12076-28666/com.myapp.tmt.app.verifier D/AlarmPingSender: Unregister alarmreceiver to MqttService13cab607-c94d-46d8-ae7f-ad889d16588f
04-18 16:45:54.259 12076-12076/com.myapp.tmt.app.verifier E/MqttHelper$initializeMq: Connection lost
                                                                                         Connection lost (32109) - java.io.EOFException
                                                                                             at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:164)
                                                                                             at java.lang.Thread.run(Thread.java:818)
                                                                                          Caused by: java.io.EOFException
                                                                                             at java.io.DataInputStream.readByte(DataInputStream.java:77)
                                                                                             at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92)
                                                                                             at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:116)
                                                                                             at java.lang.Thread.run(Thread.java:818) 
04-18 16:45:55.359 12076-28683/com.myapp.tmt.app.verifier D/AlarmPingSender: Register alarmreceiver to MqttServiceMqttService.pingSender.13cab607-c94d-46d8-ae7f-ad889d16588f
04-18 16:45:55.369 12076-12076/com.myapp.tmt.app.verifier D/MqttHelper$initializeMq: Completed connection to: tcp://demo.ticketing.myapp.com:9393| Reconnect: true
04-18 16:45:56.549 12076-28683/com.myapp.tmt.app.verifier D/AlarmPingSender: Unregister alarmreceiver to MqttService13cab607-c94d-46d8-ae7f-ad889d16588f
04-18 16:45:56.569 12076-12076/com.myapp.tmt.app.verifier E/MqttHelper$initializeMq: Connection lost
                                                                                         Connection lost (32109) - java.io.EOFException
                                                                                             at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:164)
                                                                                             at java.lang.Thread.run(Thread.java:818)
                                                                                          Caused by: java.io.EOFException
                                                                                             at java.io.DataInputStream.readByte(DataInputStream.java:77)
                                                                                             at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92)
                                                                                             at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:116)
                                                                                             at java.lang.Thread.run(Thread.java:818) 
04-18 16:45:57.699 12076-28700/com.myapp.tmt.app.verifier D/AlarmPingSender: Register alarmreceiver to MqttServiceMqttService.pingSender.13cab607-c94d-46d8-ae7f-ad889d16588f
04-18 16:45:57.709 12076-12076/com.myapp.tmt.app.verifier D/MqttHelper$initializeMq: Completed connection to: tcp://demo.ticketing.myapp.com:9393| Reconnect: true
04-18 16:46:01.679 12076-28700/com.myapp.tmt.app.verifier D/AlarmPingSender: Unregister alarmreceiver to MqttService13cab607-c94d-46d8-ae7f-ad889d16588f
04-18 16:46:01.689 12076-12076/com.myapp.tmt.app.verifier E/MqttHelper$initializeMq: Connection lost
                                                                                         Connection lost (32109) - java.io.EOFException
                                                                                             at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:164)
                                                                                             at java.lang.Thread.run(Thread.java:818)
                                                                                          Caused by: java.io.EOFException
                                                                                             at java.io.DataInputStream.readByte(DataInputStream.java:77)
                                                                                             at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92)
                                                                                             at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:116)
                                                                                             at java.lang.Thread.run(Thread.java:818) 
04-18 16:46:02.799 12076-28729/com.myapp.tmt.app.verifier D/AlarmPingSender: Register alarmreceiver to MqttServiceMqttService.pingSender.13cab607-c94d-46d8-ae7f-ad889d16588f
04-18 16:46:02.809 12076-12076/com.myapp.tmt.app.verifier D/MqttHelper$initializeMq: Completed connection to: tcp://demo.ticketing.myapp.com:9393| Reconnect: true
04-18 16:46:04.699 12076-28729/com.myapp.tmt.app.verifier D/AlarmPingSender: Unregister alarmreceiver to MqttService13cab607-c94d-46d8-ae7f-ad889d16588f
04-18 16:46:04.709 12076-12076/com.myapp.tmt.app.verifier E/MqttHelper$initializeMq: Connection lost
                                                                                         Connection lost (32109) - java.io.EOFException
                                                                                             at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:164)
                                                                                             at java.lang.Thread.run(Thread.java:818)
                                                                                          Caused by: java.io.EOFException
                                                                                             at java.io.DataInputStream.readByte(DataInputStream.java:77)
                                                                                             at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92)
                                                                                             at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:116)
                                                                                             at java.lang.Thread.run(Thread.java:818) 
04-18 16:46:05.819 12076-28749/com.myapp.tmt.app.verifier D/AlarmPingSender: Register alarmreceiver to MqttServiceMqttService.pingSender.13cab607-c94d-46d8-ae7f-ad889d16588f
04-18 16:46:05.839 12076-12076/com.myapp.tmt.app.verifier D/MqttHelper$initializeMq: Completed connection to: tcp://demo.ticketing.myapp.com:9393| Reconnect: true
04-18 16:46:07.149 12076-28749/com.myapp.tmt.app.verifier D/AlarmPingSender: Unregister alarmreceiver to MqttService13cab607-c94d-46d8-ae7f-ad889d16588f`

**Comment by KonradSzewczuk** [comment]
I've found that, i was having the same hardcoded clientID which was the cause of the infinite connect/reconnect loop. 
Here is good explanation https://github.com/knolleary/pubsubclient/issues/372

So clientId should be unique(not repeated) for all clients that are connected to the broker.
