### ISSUE TITLE
Mqtt websocket attempts to reconnect throwing EOF exception

### ISSUE THREAD

**Issue by linguokun1** [eclipse/paho.mqtt.android#306]
#358 this issue still exist

**Comment by HCMD** [comment]
请问这个问题，你找到了解决方案了吗，我这边项目也出现了相同的情况

**Comment by linguokun1** [comment]
还没找到

**Comment by SZMOFEI** [comment]
I had the same problem 。 
Maven 依赖是这个
![image](https://user-images.githubusercontent.com/29293262/110926613-96cbc300-835f-11eb-8043-622b943c090e.png)

Problem Description:

I create 5000 or 10000 mqtt clients in the loop. This problem appears in the process of rapid creation.



The exception information is as follows:
`2021-03-12 17:35:53 [ERROR] MqttException，CONNECTION_LOST  ！！！ sn SKYWAY0004057644 ,线程是 pool-1-thread-105
已断开连接 (32109) - java.io.IOException: Connection is lost.
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:197)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Connection is lost.
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:172)
	... 1 more`
