### ISSUE TITLE
mqttAndroidClient onFailure callback returns wrong exception

### ISSUE THREAD

**Issue by fdelfrari** [eclipse/paho.mqtt.android#310]
Please fill out the form below before submitting, thank you!

- [X] Bug exists Release Version 1.1.1 (Java Repository Master Branch)
- [X] Bug exists in Snapshot Version 1.1.2-SNAPSHOT (Android Service Repository Master Branch)
- [ ] Bug is just in the Sample Application.

__Android API Version Bug Seen on: API 27

__Android Version Bug Seen on:__

Please also check that if you have found the bug in the Release version (1.1.1) that you check that it also exists in the Snapshot (1.1.2-SNAPSHOT) before raising a bug.

## Description of Bug:
If I try to connect with a fake SAS Token, the exception contained into the "onFailure" callback contains error "Connection Lost (32109)" instead of "Not authorized to connect (5)"

Code to reproduce the bug:
```java
MqttConnectOptions mqttConnectOptions = new MqttConnectOptions();
mqttConnectOptions.setUserName(username);
mqttConnectOptions.setPassword("mickeyMouse");
memoryPersistence = new MemoryPersistence();
mqttAndroidClient = new MqttAndroidClient(context, mqttHost, getSource(), memoryPersistence);
mqttAndroidClient.setCallback(this);
mqttAndroidClient.connect(mqttConnectOptions, null, new IMqttActionListener() {
    @Override
    public void onSuccess(IMqttToken asyncActionToken) {..}
    @Override
    public void onFailure(IMqttToken asyncActionToken, Throwable exception) {...}
});
```

Please note that in class `ClientState.java` in package `org.eclipse.paho.client.mqttv3.internal` at line 988, the funcion:
```java
mex = ExceptionHelper.createMqttException(rc);
```
correctly sets the `MqttSecurityException` with error code `REASON_CODE_NOT_AUTHORIZED`

## Console Log output (if available):

07-23 14:53:55.656 12244-12244/com.texa.texacloud.debug E/TexaCloud: Failed to connect ssl://<MyServer> - Connessione persa
07-23 14:53:56.477 12244-12244/com.texa.texacloud.debug W/System.err: Connessione persa (32109) - java.io.EOFException
07-23 14:53:56.479 12244-12244/com.texa.texacloud.debug W/System.err:     at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:181)
07-23 14:53:56.480 12244-12244/com.texa.texacloud.debug W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
07-23 14:53:56.481 12244-12244/com.texa.texacloud.debug W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
07-23 14:53:56.482 12244-12244/com.texa.texacloud.debug W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
07-23 14:53:56.484 12244-12244/com.texa.texacloud.debug W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
07-23 14:53:56.485 12244-12244/com.texa.texacloud.debug W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
07-23 14:53:56.486 12244-12244/com.texa.texacloud.debug W/System.err:     at java.lang.Thread.run(Thread.java:764)
07-23 14:53:56.488 12244-12244/com.texa.texacloud.debug W/System.err: Caused by: java.io.EOFException
07-23 14:53:56.489 12244-12244/com.texa.texacloud.debug W/System.err:     at java.io.DataInputStream.readByte(DataInputStream.java:270)
07-23 14:53:56.490 12244-12244/com.texa.texacloud.debug W/System.err:     at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92)
07-23 14:53:56.491 12244-12244/com.texa.texacloud.debug W/System.err:     at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:133)
07-23 14:53:56.492 12244-12244/com.texa.texacloud.debug W/System.err: 	... 6 more
07-23 14:53:56.493 12244-12244/com.texa.texacloud.debug E/TexaCloud: Failed to connect ssl://<MyServer> - Connessione persa

**Comment by fdelfrari** [comment]
The issue can be resolved specifying:

```java
mqttConnectOptions.setMqttVersion(MqttConnectOptions.MQTT_VERSION_3_1_1);`
```

Closing, thanks.
