### ISSUE TITLE
support androidx

### ISSUE THREAD

**Issue by chenyp1994** [eclipse/paho.mqtt.android#321]
LocalManager in androidx (androidx.localbroadcastmanager.content.LocalBroadcastManager)
LocalManager in support (android.support.v4.content.LocalBroadcastManager)

**Comment by chintan-mishra** [comment]
This error is cryptic. Please provide more info

**Comment by chenyp1994** [comment]
MqttService.java,MqttAndroidClient.java
import android.support.v4.content.LocalBroadcastManager
replace 
import androidx.localbroadcastmanager.content.LocalBroadcastManager

**Comment by chintan-mishra** [comment]
@chenyp1994 Can you please share the steps to reproduce this error?

I am using this(Eclipse Paho Android) library in [my Android application](https://8hoot.com) where we are using AndroidX in all of the codebase maintained by us. However, some of the third party libraries have not been migrated to AndroidX and they are not giving similar errors.

**Comment by Mavirk** [comment]
@chintan-mishra 

I think im having a similar issue here 
Using android studio 3.4 
Please refer to my zips for my implementeation

Here is my error log:
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.netelek.android.mqtt, PID: 29369
    java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/content/LocalBroadcastManager;
        at org.eclipse.paho.android.service.MqttAndroidClient.registerReceiver(MqttAndroidClient.java:450)
        at org.eclipse.paho.android.service.MqttAndroidClient.connect(MqttAndroidClient.java:428)
        at org.eclipse.paho.android.service.MqttAndroidClient.connect(MqttAndroidClient.java:358)
        at com.netelek.android.mqtt.MqttAppClient.connect(MqttAppClient.java:42)
        at com.netelek.android.mqtt.MainActivity.onCreate(MainActivity.java:26)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.content.LocalBroadcastManager" on path: DexPathList[[zip file "/data/app/com.netelek.android.mqtt-7trv9XRQQ6GFhqDzfyAZGg==/base.apk"],nativeLibraryDirectories=[/data/app/com.netelek.android.mqtt-7trv9XRQQ6GFhqDzfyAZGg==/lib/x86, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at org.eclipse.paho.android.service.MqttAndroidClient.registerReceiver(MqttAndroidClient.java:450) 
        at org.eclipse.paho.android.service.MqttAndroidClient.connect(MqttAndroidClient.java:428) 
        at org.eclipse.paho.android.service.MqttAndroidClient.connect(MqttAndroidClient.java:358) 
        at com.netelek.android.mqtt.MqttAppClient.connect(MqttAppClient.java:42) 
        at com.netelek.android.mqtt.MainActivity.onCreate(MainActivity.java:26) 
        at android.app.Activity.performCreate(Activity.java:7136) 
        at android.app.Activity.performCreate(Activity.java:7127) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 

[my files.zip](https://github.com/eclipse/paho.mqtt.android/files/3121267/my.files.zip)
[MQTT.zip](https://github.com/eclipse/paho.mqtt.android/files/3121270/MQTT.zip)
the second zip is my entire project its just a simple test app that interacts with activeMQ

**Comment by Mavirk** [comment]
also please note that i am using androidX libs and I believe that is the fundamental issue because the paho project has not yet updated libg to androidX
please add an issue for updating to androidX as the old support libs will be deprecated inevitably

**Comment by easazade** [comment]
I'm having the same problem using androidx libraries

**Comment by AliKhoshraftar** [comment]
Same problem with androidx dependencies

**Comment by liduanwei** [comment]
same problem, androidx

**Comment by chenyp1994** [comment]
You can do this in file (gradle.properties)。

# Automatically convert third-party libraries to use AndroidX
android.enableJetifier=true

**Comment by JST2018** [comment]
Suggested fix isn't working.

**Comment by MayCheong** [comment]
Hi, you need to add  implementation 'androidx.legacy:legacy-support-v4:1.0.0' in your build.gradle

**Comment by raymondleta** [comment]
I honestly dont know what i did but i had the exact same problem addeed this dependancy and it worked
  implementation 'androidx.localbroadcastmanager:localbroadcastmanager:1.0.0'

**Comment by JST2018** [comment]
> Hi, you need to add implementation 'androidx.legacy:legacy-support-v4:1.0.0' in your build.gradle

That worked, thx!

**Comment by laurensius** [comment]
> Hi, you need to add implementation 'androidx.legacy:legacy-support-v4:1.0.0' in your build.gradle

That worked, thank you!

**Comment by JungVV** [comment]
Hi, I just add tlegacy-support-v4:1.0.0' and it's working well now. 
my Android studio version is 3.6.2
Thank you !!!

**Comment by rajat5559** [comment]
> Hi, you need to add implementation 'androidx.legacy:legacy-support-v4:1.0.0' in your build.gradle

Thanks, It worked for me.

**Comment by zj88163** [comment]
if 'androidx.legacy:legacy-support-v4:1.0.0' is not work, I try update 
com.android.tools.build:gradle:3.1.0 to
com.android.tools.build:gradle:3.5.1
and it worked

**Comment by trylaarsdam** [comment]
> I honestly dont know what i did but i had the exact same problem addeed this dependancy and it worked
> implementation 'androidx.localbroadcastmanager:localbroadcastmanager:1.0.0'

Thanks for the fix, it works perfectly still.

**Comment by Palmeta** [comment]
> You can do this in file (gradle.properties)。
> 
> Automatically convert third-party libraries to use AndroidX
> android.enableJetifier=true

This worked to get paho up and running!

**Comment by dewanata24** [comment]
> android.enableJetifier=true

Thanks for the fix, it **works**

**Comment by wowjames** [comment]
The same problem occurs with Aosp compilation. How do I config in Android.mk.

**Comment by nallaperumal** [comment]
I upgraded the library from v3 to MQTTv5 and issue resolved. Refer [here](https://github.com/eclipse/paho.mqtt.java/blob/master/MQTTv5.md) for MQTT v5 implementation
