### ISSUE TITLE
NullPointerException of reconnectTimer.cancel() in MqttAsyncClient class

### ISSUE THREAD

**Issue by Mokee8023** [eclipse/paho.mqtt.android#322]
Please fill out the form below before submitting, thank you!

- [ ] Bug exists Release Version 1.1.1 (Java Repository Master Branch)
version:
    implementation 'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.1.0'
    implementation 'org.eclipse.paho:org.eclipse.paho.android.service:1.1.1'

analysis:
1. BackgroundDataPreferenceReceiver in MqttService received action(android.net.conn.BACKGROUND_DATA_SETTING_CHANGED), then will excute reconnect function.
2. reconnect function will invoke reconnect function in MqttAsyncClient；
3. we will invoke stopReconnectCycle function and execute reconnectTimer.cancel(); ,but reconnectTimer variable will init in startReconnectCycle;
4. startReconnectCycle function will be invoke when connection lost.

so, the problem is mqtt isn't monitor connection lost, but received android.net.conn.BACKGROUND_DATA_SETTING_CHANGED action, then mqtt execute reconnect and invoke cancel function of reconnectTimer, but reconnectTimer is not init in this time.

__Android API Version Bug Seen on:__

__Android Version Bug Seen on:__
Android 5.1

Please also check that if you have found the bug in the Release version (1.1.1) that you check that it also exists in the Snapshot (1.1.2-SNAPSHOT) before raising a bug.

## Description of Bug: Occasionally
Occasionally

## Console Log output (if available):
10-08 13:43:12.600 27610-27610/com.iflytek.morfeiclient I/MqttConnection: Requesting Automatic reconnect using New Java AC
10-08 13:43:12.603 27610-27610/com.iflytek.morfeiclient D/AndroidRuntime: Shutting down VM
10-08 13:43:13.355 27610-27778/com.iflytek.morfeiclient I/DpmTcmClient: RegisterTcmMonitor from: com.android.okhttp.TcmIdleTimerMonitor
10-08 13:43:13.856 27610-27610/com.iflytek.morfeiclient E/AndroidRuntime: FATAL EXCEPTION: main
                                                                          Process: com.iflytek.morfeiclient, PID: 27610
                                                                          java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4000010 (has extras) } in org.eclipse.paho.android.service.MqttService$NetworkConnectionIntentReceiver@2136e4e
                                                                              at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1132)
                                                                              at android.os.Handler.handleCallback(Handler.java:751)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                              at android.os.Looper.loop(Looper.java:154)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:6133)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                                           Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.util.Timer.cancel()' on a null object reference
                                                                              at org.eclipse.paho.client.mqttv3.MqttAsyncClient.stopReconnectCycle(MqttAsyncClient.java:1120)
                                                                              at org.eclipse.paho.client.mqttv3.MqttAsyncClient.reconnect(MqttAsyncClient.java:1057)
                                                                              at org.eclipse.paho.android.service.MqttConnection.reconnect(MqttConnection.java:1049)
                                                                              at org.eclipse.paho.android.service.MqttService.reconnect(MqttService.java:342)
                                                                              at org.eclipse.paho.android.service.MqttService$NetworkConnectionIntentReceiver.onReceive(MqttService.java:827)
                                                                              at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1122)
                                                                              at android.os.Handler.handleCallback(Handler.java:751)?
                                                                              at android.os.Handler.dispatchMessage(Handler.java:95)?
                                                                              at android.os.Looper.loop(Looper.java:154)?
                                                                              at android.app.ActivityThread.main(ActivityThread.java:6133)?
                                                                              at java.lang.reflect.Method.invoke(Native Method)?
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)?
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)?
10-08 13:43:15.977 27610-27619/com.iflytek.morfeiclient E/PowerManager: WakeLock finalized while still held: MQTT

**Comment by miketran78727** [comment]
@Mokee8023 You are using version 1.1.0.  This problem was fixed in version 1.1.1 or later. Thanks.

**Comment by Mokee8023** [comment]
@miketran78727 thanks, i will test with 1.1.1 version.
