### ISSUE TITLE
java.lang.ClassCastException android.os.BinderProxy cannot be cast to org.eclipse.paho.android.service.MqttServiceBinder  org.eclipse.paho.android.service.MqttAndroidClient$MyServiceConnection.onServiceConnected(MqttAndroidClient.java:111)

### ISSUE THREAD

**Issue by Yanzhishang** [eclipse/paho.mqtt.android#328]
Please fill out the form below before submitting, thank you!

- [ ] Bug exists Release Version 1.1.1 (Java Repository Master Branch)
- [ ] Bug exists in Snapshot Version 1.1.2-SNAPSHOT (Android Service Repository Master Branch)
- [ ] Bug is just in the Sample Application.

__Android API Version Bug Seen on:__

__Android Version Bug Seen on:__

Please also check that if you have found the bug in the Release version (1.1.1) that you check that it also exists in the Snapshot (1.1.2-SNAPSHOT) before raising a bug.

## Description of Bug:
E.g. Steps to re-create, how often does this happen etc..

**Comment by JeremeLau** [comment]
Same issue here

Android API Version Bug Seen on:  
  26 in my test 

Android Version Bug Seen on:
  Bug exists Release Version 1.1.1 

Description of Bug:
I have 2 services and want 2 create them in different process, then issue 

Console Log output (if available):

`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.guoguang.ticwatch, PID: 9630
    java.lang.ClassCastException: android.os.BinderProxy cannot be cast to org.eclipse.paho.android.service.MqttServiceBinder
        at org.eclipse.paho.android.service.MqttAndroidClient$MyServiceConnection.onServiceConnected(MqttAndroidClient.java:111)
        at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1634)
        at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1663)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)`

**Comment by divyaksh-shukla** [comment]
There is a solution available on stackoverflow.
https://stackoverflow.com/a/48878872/7587116
I don't know how relevant the fix is or will it work or not. The issue is still visible on version 1.1.1 and version 1.1.2-SNAPSHOT. I'm also using this library the same way as @JeremeLau to create a notification service library making it totally independent of Firebase notifications. Please let me know if there are additional details required to provide a fix for the above issue.

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.divyakshshukla.myhelperjava:mqttNotificationServiceProcess, PID: 6480
    java.lang.ClassCastException: android.os.BinderProxy cannot be cast to org.eclipse.paho.android.service.MqttServiceBinder
        at org.eclipse.paho.android.service.MqttAndroidClient$MyServiceConnection.onServiceConnected(MqttAndroidClient.java:111)
        at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1730)
        at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1762)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```
