### ISSUE TITLE
Not authorized to connect (5) when connecting with Amazon MQ

### ISSUE THREAD

**Issue by pfuentespazos** [eclipse/paho.mqtt.android#329]
Please fill out the form below before submitting, thank you!

- [ ] Bug exists Release Version 1.1.1 (Java Repository Master Branch)
- [ ] Bug exists in Snapshot Version 1.1.2-SNAPSHOT (Android Service Repository Master Branch)
- [ ] Bug is just in the Sample Application.

__Android API Version Bug Seen on:__

__Android Version Bug Seen on:__

Please also check that if you have found the bug in the Release version (1.1.1) that you check that it also exists in the Snapshot (1.1.2-SNAPSHOT) before raising a bug.

## Description of Bug:
I'm having an issue when trying to connect to broker that I created in AmazonMQ. I have implemented the client in Android following the sample. I have tried to connect to other brokers like CloudMQTT and it was working fine, but when I try to connect to the one hosted in Amazon it throws a "Not authorized to connect" error.

I have double (and triple) check the user and pasword and everything is correct.

## Console Log output (if available):

mk.wsd D/AlarmPingSender: Unregister alarmreceiver to MqttServiceTestClient2102
mk.wsd D/WSDemo-DEV: MQManager - Connection with MQTT FAILED
mk.wsd W/System.err: Not authorized to connect (5)
mk.wsd W/System.err:     at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:28)
mk.wsd W/System.err:     at org.eclipse.paho.client.mqttv3.internal.ClientState.notifyReceivedAck(ClientState.java:973)
mk.wsd W/System.err:     at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:128)
mk.wsd W/System.err:     at java.lang.Thread.run(Thread.java:764)

I have used the URI that appears in AmazonMQ site:

![image](https://user-images.githubusercontent.com/45077852/48574188-ce044380-e90e-11e8-9826-da6e4eed0143.png)

And I configured the client as follows:

private static MQManager mInstance = null;
private String clientId = "TestClient";
public final String serverURI = "ssl://b-a6xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx:8883" ; 
private final String publishTopic = "testData";
public static final String userName = "admin";
public static final String password = "xxxxxxxxxxxx";
MqttConnectOptions connectOptions = new MqttConnectOptions();
        connectOptions.setMqttVersion(MqttConnectOptions.MQTT_VERSION_3_1_1);
        connectOptions.setAutomaticReconnect(true);
        connectOptions.setCleanSession(true);
        connectOptions.setUserName(userName);
        connectOptions.setPassword(password.toCharArray());

[..]

client =  new MqttAndroidClient(mContext, serverURI, clientId);
            client.setCallback(mqttCallback);
client.connect(connectOptions, new IMqttActionListener(){
                @Override
                public void onSuccess(IMqttToken asyncActionToken) {
                    Log.d(APPTAG, "MQManager - Connection with MQTT SUCCESS");
                }

                @Override
                public void onFailure(IMqttToken asyncActionToken, Throwable exception) {
                    Log.d(APPTAG, "MQManager - Connection with MQTT FAILED");
                    exception.printStackTrace();
                }
            });

Is there any particular configuration that needs to be considered for AmazonMQ? Many thanks in advacnce.

**Comment by chintan-mishra** [comment]
Are you able to connect with AmazonMQ using MosquittoCLI or [MQTT-spy](https://github.com/eclipse/paho.mqtt-spy)?

**Comment by iarechagaMM** [comment]
I am having the very same error. Did you manage to solve it @pfuentespazos?

**Comment by pfuentes-mk** [comment]
Hi Ignacio, I solved it by using the class MqttClient instead of the MqttAndroidClient. Hope it works.
