### ISSUE TITLE
Stop service and cause leakage

### ISSUE THREAD

**Issue by LinYh08** [eclipse/paho.mqtt.android#366]
Stop service and cause leakage

- [ ] Bug exists Release Version3.1.1 (Java Repository Master Branch)

Stop service and cause leakage

logcat ：
2019-06-06 15:20:51.542 18926-18926/com.example.myapplication E/ActivityThread: Service com.example.myapplication.MQttService1 has leaked ServiceConnection org.eclipse.paho.android.service.MqttAndroidClient$MyServiceConnection@f277926 that was originally bound here
android.app.ServiceConnectionLeaked: Service com.example.myapplication.MQttService1 has leaked ServiceConnection org.eclipse.paho.android.service.MqttAndroidClient$MyServiceConnection@f277926 that was originally bound here
at android.app.LoadedApk$ServiceDispatcher.(LoadedApk.java:1532)
at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:1424)
at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1605)
at android.app.ContextImpl.bindService(ContextImpl.java:1557)
at android.content.ContextWrapper.bindService(ContextWrapper.java:684)
at org.eclipse.paho.android.service.MqttAndroidClient.connect(MqttAndroidClient.java:425)
at com.example.myapplication.MQttService1.doClientConnection(MQttService1.java:138)
at com.example.myapplication.MQttService1.init(MQttService1.java:129)
at com.example.myapplication.MQttService1.onCreate(MQttService1.java:181)
at android.app.ActivityThread.handleCreateService(ActivityThread.java:3339)
at android.app.ActivityThread.-wrap4(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1677)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6494)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

I call function to stop service.
stopService(new Intent(getActivity(), MQttService1.class));

Please check code MQttService1.java

@Override
public void onDestroy() {
    Log.e(TAG, "onDestroy: "+"servicer" );
    try {
        client.unsubscribe(topicArray);
        client.disconnect();
    } catch (MqttException e) {
        e.printStackTrace();
    }
    //stopSelf();
    super.onDestroy();
}

**Comment by Ryanauger95** [comment]
I have this same issue. My app crashes whenever I try to close the client...

**Comment by Ryanauger95** [comment]
No idea what to do

**Comment by caktoy** [comment]
Me too, I have same issue, is there any solution?
