### ISSUE TITLE
android support 4 class not found

### ISSUE THREAD

**Issue by mstranne** [eclipse/paho.mqtt.android#378]
I am built an android lib (aar) using MqttAndroidClient inside an Unity Application.
The library is working fine when only builing a AndroidStudio application, but when using the library inside an Unity Application I get following exception:

`07-16 12:24:32.045 26595-26694/com.ar4.mqttServer E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
    Process: com.ar4.mqttServer, PID: 26595
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:354)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/content/LocalBroadcastManager;
        at org.eclipse.paho.android.service.MqttAndroidClient.registerReceiver(MqttAndroidClient.java:450)
        at org.eclipse.paho.android.service.MqttAndroidClient.connect(MqttAndroidClient.java:428)
        at com.ar4.ntripclient.NtripClient$NTRIPClientThread.doInBackground(NtripClient.java:100)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.content.LocalBroadcastManager" on path: DexPathList[[zip file "/data/app/com.ar4.mqttServer-VgOSmd2Z48DauZHuv9wyuQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.ar4.mqttServer-VgOSmd2Z48DauZHuv9wyuQ==/lib/arm, /data/app/com.ar4.mqttServer-VgOSmd2Z48DauZHuv9wyuQ==/base.apk!/lib/armeabi-v7a, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:171)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at org.eclipse.paho.android.service.MqttAndroidClient.registerReceiver(MqttAndroidClient.java:450) 
        at org.eclipse.paho.android.service.MqttAndroidClient.connect(MqttAndroidClient.java:428) 
        at com.ar4.ntripclient.NtripClient$NTRIPClientThread.doInBackground(NtripClient.java:100) 
        at android.os.AsyncTask$2.call(AsyncTask.java:333) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) `

However, I tried importing the android-support-v4.jar but that did not made any difference.

Any idea how to solve this problem?

**Comment by chenyp1994** [comment]
#321

**Comment by JST2018** [comment]
The suggested fix in #321 isn't working (for me).

**Comment by JST2018** [comment]
See here, for me it worked:
https://github.com/eclipse/paho.mqtt.android/issues/321#issuecomment-533602703
