### ISSUE TITLE
how to close the pingpong broadcast

### ISSUE THREAD

**Issue by Key-CN** [eclipse/paho.mqtt.android#386]
Please fill out the form below before submitting, thank you!

- [✅] Bug exists Release Version 1.1.1 (Java Repository Master Branch)
- [ ] Bug exists in Snapshot Version 1.1.2-SNAPSHOT (Android Service Repository Master Branch)
- [ ] Bug is just in the Sample Application.

__Android API Version Bug Seen on:__29

__Android Version Bug Seen on:_29_

Please also check that if you have found the bug in the Release version (1.1.1) that you check that it also exists in the Snapshot (1.1.2-SNAPSHOT) before raising a bug.

## Description of Bug:
System app can't send  non-protected broadcast,how to close the pingpong broadcast

## Console Log output (if available):
```
2019-11-06 20:19:02.298 system_process E/ActivityManager: Sending non-protected broadcast MqttService.pingSender.GID_AI_Classroom@@@c1a3687771872fe5 from system uid 1000 pkg com.ishow.tv.launcher
    java.lang.Throwable
        at com.android.server.am.ActivityManagerService.checkBroadcastFromSystem(ActivityManagerService.java:18153)
        at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:18720)
        at com.android.server.am.ActivityManagerService.broadcastIntentInPackage(ActivityManagerService.java:18833)
        at com.android.server.am.PendingIntentRecord.sendInner(PendingIntentRecord.java:308)
        at com.android.server.am.PendingIntentRecord.sendWithResult(PendingIntentRecord.java:205)
        at com.android.server.am.ActivityManagerService.sendIntentSender(ActivityManagerService.java:7414)
        at android.app.PendingIntent.send(PendingIntent.java:836)
        at com.android.server.AlarmManagerService$DeliveryTracker.deliverLocked(AlarmManagerService.java:3145)
        at com.android.server.AlarmManagerService.deliverAlarmsLocked(AlarmManagerService.java:2581)
        at com.android.server.AlarmManagerService$AlarmThread.run(AlarmManagerService.java:2702)
2019-11-06 20:19:02.309 com.ishow.tv.launcher D/AlarmPingSender: Sending Ping at:1573042742309
2019-11-06 20:19:02.314 com.ishow.tv.launcher D/AlarmPingSender: Schedule next alarm at 1573042802313
2019-11-06 20:19:02.314 com.ishow.tv.launcher D/AlarmPingSender: Alarm scheule using setExactAndAllowWhileIdle, next: 60000
2019-11-06 20:19:02.345 com.ishow.tv.launcher D/AlarmPingSender: Success. Release lock(MqttService.client.GID_AI_Classroom@@@c1a3687771872fe5):1573042742345
```

**Comment by EvanZch** [comment]
> Please fill out the form below before submitting, thank you!
> 
> * [white_check_mark] Bug exists Release Version 1.1.1 (Java Repository Master Branch)
> * [ ]  Bug exists in Snapshot Version 1.1.2-SNAPSHOT (Android Service Repository Master Branch)
> * [ ]  Bug is just in the Sample Application.
> 
> __Android API Version Bug Seen on:__29
> 
> __Android Version Bug Seen on:_29_
> 
> Please also check that if you have found the bug in the Release version (1.1.1) that you check that it also exists in the Snapshot (1.1.2-SNAPSHOT) before raising a bug.
> 
> ## Description of Bug:
> System app can't send non-protected broadcast,how to close the pingpong broadcast
> 
> ## Console Log output (if available):
> ```
> 2019-11-06 20:19:02.298 system_process E/ActivityManager: Sending non-protected broadcast MqttService.pingSender.GID_AI_Classroom@@@c1a3687771872fe5 from system uid 1000 pkg com.ishow.tv.launcher
>     java.lang.Throwable
>         at com.android.server.am.ActivityManagerService.checkBroadcastFromSystem(ActivityManagerService.java:18153)
>         at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:18720)
>         at com.android.server.am.ActivityManagerService.broadcastIntentInPackage(ActivityManagerService.java:18833)
>         at com.android.server.am.PendingIntentRecord.sendInner(PendingIntentRecord.java:308)
>         at com.android.server.am.PendingIntentRecord.sendWithResult(PendingIntentRecord.java:205)
>         at com.android.server.am.ActivityManagerService.sendIntentSender(ActivityManagerService.java:7414)
>         at android.app.PendingIntent.send(PendingIntent.java:836)
>         at com.android.server.AlarmManagerService$DeliveryTracker.deliverLocked(AlarmManagerService.java:3145)
>         at com.android.server.AlarmManagerService.deliverAlarmsLocked(AlarmManagerService.java:2581)
>         at com.android.server.AlarmManagerService$AlarmThread.run(AlarmManagerService.java:2702)
> 2019-11-06 20:19:02.309 com.ishow.tv.launcher D/AlarmPingSender: Sending Ping at:1573042742309
> 2019-11-06 20:19:02.314 com.ishow.tv.launcher D/AlarmPingSender: Schedule next alarm at 1573042802313
> 2019-11-06 20:19:02.314 com.ishow.tv.launcher D/AlarmPingSender: Alarm scheule using setExactAndAllowWhileIdle, next: 60000
> 2019-11-06 20:19:02.345 com.ishow.tv.launcher D/AlarmPingSender: Success. Release lock(MqttService.client.GID_AI_Classroom@@@c1a3687771872fe5):1573042742345
> ```

请问处理了吗？系统应用中应该就会出现这个问题

**Comment by mishuprovince** [comment]
do you have any solution for the question?

**Comment by mishuprovince** [comment]
> > Please fill out the form below before submitting, thank you!
> > 
> > * [white_check_mark] Bug exists Release Version 1.1.1 (Java Repository Master Branch)
> > * [ ]   Bug exists in Snapshot Version 1.1.2-SNAPSHOT (Android Service Repository Master Branch)
> > * [ ]   Bug is just in the Sample Application.
> > 
> > __Android API Version Bug Seen on:__29
> > __Android Version Bug Seen on:_29_
> > Please also check that if you have found the bug in the Release version (1.1.1) that you check that it also exists in the Snapshot (1.1.2-SNAPSHOT) before raising a bug.
> > ## Description of Bug:
> > System app can't send non-protected broadcast,how to close the pingpong broadcast
> > ## Console Log output (if available):
> > ```
> > 2019-11-06 20:19:02.298 system_process E/ActivityManager: Sending non-protected broadcast MqttService.pingSender.GID_AI_Classroom@@@c1a3687771872fe5 from system uid 1000 pkg com.ishow.tv.launcher
> >     java.lang.Throwable
> >         at com.android.server.am.ActivityManagerService.checkBroadcastFromSystem(ActivityManagerService.java:18153)
> >         at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:18720)
> >         at com.android.server.am.ActivityManagerService.broadcastIntentInPackage(ActivityManagerService.java:18833)
> >         at com.android.server.am.PendingIntentRecord.sendInner(PendingIntentRecord.java:308)
> >         at com.android.server.am.PendingIntentRecord.sendWithResult(PendingIntentRecord.java:205)
> >         at com.android.server.am.ActivityManagerService.sendIntentSender(ActivityManagerService.java:7414)
> >         at android.app.PendingIntent.send(PendingIntent.java:836)
> >         at com.android.server.AlarmManagerService$DeliveryTracker.deliverLocked(AlarmManagerService.java:3145)
> >         at com.android.server.AlarmManagerService.deliverAlarmsLocked(AlarmManagerService.java:2581)
> >         at com.android.server.AlarmManagerService$AlarmThread.run(AlarmManagerService.java:2702)
> > 2019-11-06 20:19:02.309 com.ishow.tv.launcher D/AlarmPingSender: Sending Ping at:1573042742309
> > 2019-11-06 20:19:02.314 com.ishow.tv.launcher D/AlarmPingSender: Schedule next alarm at 1573042802313
> > 2019-11-06 20:19:02.314 com.ishow.tv.launcher D/AlarmPingSender: Alarm scheule using setExactAndAllowWhileIdle, next: 60000
> > 2019-11-06 20:19:02.345 com.ishow.tv.launcher D/AlarmPingSender: Success. Release lock(MqttService.client.GID_AI_Classroom@@@c1a3687771872fe5):1573042742345
> > ```
> 
> 请问处理了吗？系统应用中应该就会出现这个问题

>同问+1

**Comment by june5753** [comment]
同问+1

**Comment by hua109209** [comment]
mark for response

**Comment by libinll** [comment]
各位都怎么处理这个问题的，可否分享一下

**Comment by Key-CN** [comment]
快两年前的问题了。最终是在源码里加入了这个广播的白名单。瑞芯微rk3399-Android7.1的系统

**Comment by egbertwong** [comment]
遇到一样的问题，应该只能在源码里面添加白名单来解决了
