### ISSUE TITLE
Android 4.2.2   Static storage paths aren't available from AID_SYSTEM

### ISSUE THREAD

**Issue by EvanZch** [eclipse/paho.mqtt.android#387]
Static storage paths aren't available from AID_SYSTEM
    java.lang.Throwable
        at android.os.Environment.throwIfSystem(Environment.java:812)
        at android.os.Environment.getExternalStorageAppFilesDirectory(Environment.java:602)
        at android.app.ContextImpl.getExternalFilesDir(ContextImpl.java:784)
        at android.content.ContextWrapper.getExternalFilesDir(ContextWrapper.java:198)
        at org.eclipse.paho.android.service.MqttConnection.connect(MqttConnection.java:219)
        at org.eclipse.paho.android.service.MqttService.connect(MqttService.java:329)
        at org.eclipse.paho.android.service.MqttAndroidClient.doConnect(MqttAndroidClient.java:467)
        at org.eclipse.paho.android.service.MqttAndroidClient.access$200(MqttAndroidClient.java:76)
        at org.eclipse.paho.android.service.MqttAndroidClient$MyServiceConnection.onServiceConnected(MqttAndroidClient.java:115)
        at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1101)
        at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1118)
        at android.os.Handler.handleCallback(Handler.java:725)
        at android.os.Handler.dispatchMessage(Handler.java:92)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:5041)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
        at dalvik.system.NativeStart.main(Native Method)

**Comment by EvanZch** [comment]
org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.2   error
org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.0    ok
