### ISSUE TITLE
ProGuard-related "no NetworkModule installed for scheme xx" issue

### ISSUE THREAD

**Issue by davidevertuani** [eclipse/paho.mqtt.android#398]
- [x] Bug exists Release Version 1.2.2
- [x] Bug exists Release Version 1.2.1
- [ ] Bug exists Release Version 1.2.0

## Description of Bug:
I'm having problems with the following exception:
`java.lang.IllegalArgumentException: no NetworkModule installed for scheme "tcp" of URI "tcp://your.url:1883"`.
Seems similar to [paho.mqtt.java issue #572](https://github.com/eclipse/paho.mqtt.java/issues/572).
Version `1.2.2` worked just fine until I upgraded Android Studio (and therefore Gradle) to 3.6.1; now compiled .apk with `minifyEnabled true` throw the aforemntioned issue.
As far as I noticed the issue was NOT present with version `1.2.2` and lower gradle versions.

## How to reproduce
With version `1.2.2` or `1.2.1` create a new connection (using schemas `tcp, ssl, ws` was the same for me).
Compile a signed apk - or run a debug version **with** `minifiyEnabled true` - the issue does not show when ProGuard/R8 is disabled.

## Workarounds
Downgrading to `1.2.0` solves this issue but introduces another one (connections over WebSocket disconnecting and reconnecting in loop) so it's not a viable solution for production.

Disabling ProGuard, i.e. `minifyEnabled false` solves the problem with version `1.2.2` and `1.2.1` but not obfuscating the code is not viable for production.

As it seems related to ProGuard I tried adding the following to `proguard-rules.pro`, but that didn't help:
```
 -keep class org.eclipse.paho.client.** { *; }
 -keep class org.eclipse.paho.android.service.** { *; }
 -keepclasseswithmembers class org.eclipse.paho.** {*;}
```

Any help would be much appreciated. Thanks!

## Console Log output:
```
W/System.err: java.lang.IllegalArgumentException: no NetworkModule installed for scheme "ws" of URI "ws://test.mosquitto.org:8080"
W/System.err:     at f.a.a.a.a.v.o.a(:70)
        at f.a.a.a.a.h.<init>(:454)
        at f.a.a.a.a.h.<init>(:320)
        at org.eclipse.paho.android.service.e.a(:289)
        at org.eclipse.paho.android.service.MqttService.a(:329)
        at org.eclipse.paho.android.service.d.f(:467)
        at org.eclipse.paho.android.service.d.a(:76)
        at org.eclipse.paho.android.service.d$c.onServiceConnected(:115)
        at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1730)
        at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1762)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
W/System.err: java.lang.IllegalArgumentException: no NetworkModule installed for scheme "ssl" of URI "ssl://test.mosquitto.org:8883"
W/System.err:     at f.a.a.a.a.v.o.a(:70)
        at f.a.a.a.a.h.<init>(:454)
W/System.err:     at f.a.a.a.a.h.<init>(:320)
        at org.eclipse.paho.android.service.e.a(:289)
        at org.eclipse.paho.android.service.MqttService.a(:329)
        at org.eclipse.paho.android.service.d.f(:467)
        at org.eclipse.paho.android.service.d.a(:76)
W/System.err:     at org.eclipse.paho.android.service.d$c.onServiceConnected(:115)
        at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1730)
W/System.err:     at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1762)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by dzysghr** [comment]
I tried adding the following rules, it works for me 

```
-keep class org.eclipse.paho.client.mqttv3.** {*;}
-keep class org.eclipse.paho.android.service.** { *; }
-keepclasseswithmembers class org.eclipse.paho.** {*;}
```

**Comment by davidevertuani** [comment]
Thanks @dzysghr.
I wasn't able to get it working with Gradle plugin version 3.6.1, however with v. 3.6.2 everything works properly.
