### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'long org.eclipse.paho.client.mqttv3.internal.ClientState.getKeepAlive()' on a null object reference

### ISSUE THREAD

**Issue by BarretWu** [eclipse/paho.mqtt.android#424]
Please fill out the form below before submitting, thank you!

- [ ] Bug exists Release Version 1.2.5 (Java Repository Master Branch)

java.lang.NullPointerException: Attempt to invoke virtual method &#39;long org.eclipse.paho.client.mqttv3.internal.ClientState.getKeepAlive()&#39; on a null object reference
	at org.eclipse.paho.client.mqttv3.internal.ClientComms.getKeepAlive(ClientComms.java:654)
	at org.eclipse.paho.android.service.AlarmPingSender.start(AlarmPingSender.java:79)
	at org.eclipse.paho.client.mqttv3.internal.ClientState.connected(ClientState.java:1201)
	at org.eclipse.paho.client.mqttv3.internal.ClientState.notifyReceivedAck(ClientState.java:1037)
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:150)
	at java.lang.Thread.run(Thread.java:764)

## Description of Bug:
E.g. Steps to re-create, how often does this happen etc..

**Comment by drachim-dev** [comment]
Same error happened to me with current version

**Comment by Basitshaabaz** [comment]
The same error happened to me on the version 3.6.0-beta1
