### ISSUE TITLE
Error: Has leaked IntentReceiver org.eclipse.paho.android.service.AlarmPingSender

### ISSUE THREAD

**Issue by darlandc1998** [eclipse/paho.mqtt.android#431]
Please fill out the form below before submitting, thank you!

- [ ] Bug exists Release Version 1.1.1 (Java Repository Master Branch)
- [ ] Bug exists in Snapshot Version 1.1.2-SNAPSHOT (Android Service Repository Master Branch)
- [X] Bug is just in the Sample Application.

__Android API Version Bug Seen on:__

__Android Version Bug Seen on:__

Please also check that if you have found the bug in the Release version (1.1.1) that you check that it also exists in the Snapshot (1.1.2-SNAPSHOT) before raising a bug.

## Description of Bug:
Hello, I created a notification service that uses an MqttAndroidClient, when starting MainActivity.class I start the notification service (startService) that is running in the background and in the foreground, when calling onDestroy of that same activity (MainActivity.class) to stop notification service (stopService), and within the notification service onDestroy I stop running MqttAndroidClient, however when I run the methods to stop running, the following exception is thrown:

`Service org.eclipse.paho.android.service.MqttService has leaked IntentReceiver org.eclipse.paho.android.service.AlarmPingSender$AlarmReceiver@b2f2c97 that was originally registered here. Are you missing a call to unregisterReceiver ()?`

I perform the following methods to stop MqttAndroidClient from running:

```
client.unregisterResources();
client.close();
client.disconnect(0);
client.setCallback(null);
```

Any idea what could be causing this?

## Console Log output (if available):
```
2020-09-06 16:35:32.250 12888-13124/com.example.ktrine D/AlarmPingSender: Unregister alarmreceiver to MqttServicepaho62240772986001
2020-09-06 16:35:32.257 12888-12888/com.example.ktrine E/ActivityThread: Service org.eclipse.paho.android.service.MqttService has leaked IntentReceiver org.eclipse.paho.android.service.AlarmPingSender$AlarmReceiver@b2f2c97 that was originally registered here. Are you missing a call to unregisterReceiver()?
    android.app.IntentReceiverLeaked: Service org.eclipse.paho.android.service.MqttService has leaked IntentReceiver org.eclipse.paho.android.service.AlarmPingSender$AlarmReceiver@b2f2c97 that was originally registered here. Are you missing a call to unregisterReceiver()?
        at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1360)
        at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:1141)
        at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1436)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1397)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1385)
        at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:609)
        at org.eclipse.paho.android.service.AlarmPingSender.start(AlarmPingSender.java:72)
        at org.eclipse.paho.client.mqttv3.internal.ClientState.connected(ClientState.java:1041)
        at org.eclipse.paho.client.mqttv3.internal.ClientState.notifyReceivedAck(ClientState.java:882)
        at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:118)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by CrazyMo** [comment]
【Version】 :
    implementation 'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.3'
    implementation 'org.eclipse.paho:org.eclipse.paho.android.service:1.1.1'


I try to create two Client （ with 4G and Lan Network） 
MqttAndroidClient 4gClient=new MqttAndroidClient (...);，lanClient=new MqttAndroidClient (...);
4gClient.connect();

，when I try do disconnect Lan Cilent in the HandlerThread，like this:
lanClient.disconnect();

 public synchronized void disconnect() {
        if (mMqttAndroidClient != null) {
            try {
                mMqttAndroidClient.unregisterResources();
                mMqttAndroidClient.close();
                mMqttAndroidClient.disconnect(0);
                mMqttAndroidClient.setCallback(null);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
}
Log :
09-17 16:12:33.741 D/LAMY.MqttProxy->( 1003): $$【NETWORK】disconnect MqttClient->MqttProxy$$
09-17 16:12:33.795 D/AlarmPingSender( 1003): Unregister alarmreceiver to MqttServiceGSJ12345_4g
09-17 16:12:33.797 E/ActivityThread( 1003): Service org.eclipse.paho.android.service.MqttService has leaked IntentReceiver org.eclipse.paho.android.service.AlarmPingSender$AlarmReceiver@c50f9e9 that was originally registered here. Are you missing a call to unregisterReceiver()?
09-17 16:12:33.797 E/ActivityThread( 1003): android.app.IntentReceiverLeaked: Service org.eclipse.paho.android.service.MqttService has leaked IntentReceiver org.eclipse.paho.android.service.AlarmPingSender$AlarmReceiver@c50f9e9 that was originally registered here. Are you missing a call to unregisterReceiver()?
09-17 16:12:33.797 E/ActivityThread( 1003): 	at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1159)
09-17 16:12:33.797 E/ActivityThread( 1003): 	at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:946)
09-17 16:12:33.797 E/ActivityThread( 1003): 	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1302)
09-17 16:12:33.797 E/ActivityThread( 1003): 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1282)
09-17 16:12:33.797 E/ActivityThread( 1003): 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1276)
09-17 16:12:33.797 E/ActivityThread( 1003): 	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:586)
09-17 16:12:33.797 E/ActivityThread( 1003): 	at org.eclipse.paho.android.service.AlarmPingSender.start(AlarmPingSender.java:74)
09-17 16:12:33.797 E/ActivityThread( 1003): 	at org.eclipse.paho.client.mqttv3.internal.ClientState.connected(ClientState.java:1209)
09-17 16:12:33.797 E/ActivityThread( 1003): 	at org.eclipse.paho.client.mqttv3.internal.ClientState.notifyReceivedAck(ClientState.java:1045)
09-17 16:12:33.797 E/ActivityThread( 1003): 	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:151)

**Comment by Alexminator99** [comment]
Im also having the same error. Any updates on this?

**Comment by CrazyMo** [comment]
,,发自我的手机-------- 原始邮件 --------发件人： Alexminator99 ***@***.***>日期： 2024年4月4日周四 10:37收件人： "eclipse/paho.mqtt.android" ***@***.***>抄送： CrazyMo ***@***.***>, Comment ***@***.***>主    题： Re: [eclipse/paho.mqtt.android] Error: Has leaked IntentReceiver org.eclipse.paho.android.service.AlarmPingSender (#431)
Im also having the same error. Any updates on this?
