### ISSUE TITLE
java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter exception

### ISSUE THREAD

**Issue by mohanbright** [eclipse/paho.mqtt.android#433]
java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter exception
        at com.zoptal.drivilldriver.Utilities.AppService$subscribe$1.onFailure(Unknown Source:7)
        at org.eclipse.paho.android.service.MqttTokenAndroid.notifyFailure(MqttTokenAndroid.java:146)
        at org.eclipse.paho.android.service.MqttAndroidClient.simpleAction(MqttAndroidClient.java:1501)
        at org.eclipse.paho.android.service.MqttAndroidClient.subscribeAction(MqttAndroidClient.java:1526)
        at org.eclipse.paho.android.service.MqttAndroidClient.onReceive(MqttAndroidClient.java:1377)
        at androidx.localbroadcastmanager.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:313)
        at androidx.localbroadcastmanager.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:121)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

getting this error while subscibing to a topic
--

this is how I am subscribing-

mqttAndroidClient!!.subscribe(topic, qos, null, object : IMqttActionListener {
                override fun onSuccess(asyncActionToken: IMqttToken) {
                    // Give your callback on Subscription here

                    // Give your callback on Subscription here
                    Log.d("Subscribe", "Success $topic")
                }
                override fun onFailure(
                        asyncActionToken: IMqttToken,
                        exception: Throwable
                ) {
                    // Give your subscription failure callback here

                    // Give your subscription failure callback here
                    Log.d("Subscribe", "FAILED $topic "+exception.localizedMessage)
                }
            })

**Comment by zhangshuai88** [comment]
i also  meet this problem，have you solved？

```
E AndroidRuntime: java.lang.NullPointerException: Parameter specified as non-null is null: method f2.i.e, parameter exception
E AndroidRuntime: 	at u0.a$d.a(Unknown Source:7)
E AndroidRuntime: 	at org.eclipse.paho.android.service.g.f(MqttTokenAndroid.java:10)
E AndroidRuntime: 	at org.eclipse.paho.android.service.MqttAndroidClient.z(MqttAndroidClient.java:5)
E AndroidRuntime: 	at org.eclipse.paho.android.service.MqttAndroidClient.C(MqttAndroidClient.java:2)
E AndroidRuntime: 	at org.eclipse.paho.android.service.MqttAndroidClient.onReceive(MqttAndroidClient.java:13)
E AndroidRuntime: 	at z.a.a(LocalBroadcastManager.java:12)
E AndroidRuntime: 	at z.a$a.handleMessage(LocalBroadcastManager.java:3)
E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7704)
E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
E AndroidRuntime: 	at `com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)`
E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```
