### ISSUE TITLE
UNEXPECTED TOP-LEVEL EXCEPTION: 17:06:09 com.android.dx.cf.iface.ParseException:   while building with AOSP Nougat make build system. (NOT an issue for OREO make build system)

### ISSUE THREAD

**Issue by koushikDeb** [eclipse/paho.mqtt.android#458]
Please fill out the form below before submitting, thank you!

- [ NA] Bug exists Release Version 1.1.1 (Java Repository Master Branch)
- [ NA] Bug exists in Snapshot Version 1.1.2-SNAPSHOT (Android Service Repository Master Branch)
- [ No] Bug is just in the Sample Application.

__Android API Version Bug Seen on:__ API level 25

__Android Version Bug Seen on:__ 7

Please also check that if you have found the bug in the Release version (1.1.1) that you check that it also exists in the Snapshot (1.1.2-SNAPSHOT) before raising a bug.
Yes

## Description of Bug:
**Using mqttv3 1.2.5 for android in AOSP(Nougat) System Application and getting **UNEXPECTED TOP-LEVEL EXCEPTION:**
from make build system.** 
**NOTE:** same code and .mk  library is working fine for Oreo in system application. 
**NOTE 2:** For Nougat build system uses java 1.7 and for Oreo it uses 1.8 

**Android.mk content**

    LOCAL_STATIC_JAVA_LIBRARIES += android-support-v4 \
    libRetrofit2 \
    libGson \
    libGsonConverter \
    libOkie \
    libOkhttp \
    pahoClientMqttV3 \
    pahoAndroidService
    
    include $(BUILD_PACKAGE)
    
    include $(CLEAR_VARS)
    
    
    LOCAL_PREBUILT_STATIC_JAVA_LIBRARIES := \
    libGsonConverter:libs/converter-gson-2.5.0.jar \
    libGson:libs/gson-2.8.1.jar \
    libRetrofit2:libs/retrofit-2.5.0.jar \
    libOkie:libs/okio-1.15.0.jar \
    libOkhttp:libs/okhttp-3.12.0.jar \
    pahoClientMqttV3:libs/org.eclipse.paho.client.mqttv3-1.2.5.jar \
    pahoAndroidService:libs/org.eclipse.paho.android.service-1.1.1.jar
     `

## Console Log output (if available):
```

UNEXPECTED TOP-LEVEL EXCEPTION:
17:06:09 com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)
17:06:09 	at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:472)
17:06:09 	at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)
17:06:09 	at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)
17:06:09 	at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)
17:06:09 	at com.android.dx.command.dexer.Main.processClass(Main.java:704)
17:06:09 	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:673)
17:06:09 	at com.android.dx.command.dexer.Main.access$300(Main.java:83)
17:06:09 	at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:602)
17:06:09 	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
17:06:09 	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
17:06:09 	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
17:06:09 	at com.android.dx.command.dexer.Main.processOne(Main.java:632)
17:06:09 	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:510)
17:06:09 	at com.android.dx.command.dexer.Main.runMultiDex(Main.java:334)
17:06:09 	at com.android.dx.command.dexer.Main.run(Main.java:244)
17:06:09 	at com.android.dx.command.dexer.Main.main(Main.java:215)
17:06:09 	at com.android.dx.command.Main.main(Main.java:106)
17:06:09 ...while parsing org/eclipse/paho/client/mqttv3/internal/websocket/WebSocketSecureNetworkModuleFactory.class


```

**Comment by hannesa2** [comment]
Does it happen with https://github.com/hannesa2/paho.mqtt.android too ?
