### ISSUE TITLE
MqttException (0) - java.io.FileNotFoundException: /mnt/sdcard/Android/data/com.iflytek.autofly.feedback/files/MqttConnection/1__631e8f988bbdcbe3-sslusercomp1mycherycom10075/s-8.msg: open failed: ENOENT (No such file or directory)

### ISSUE THREAD

**Issue by damo2** [eclipse/paho.mqtt.android#463]
Please fill out the form below before submitting, thank you!

- [ ] Bug exists Release Version 1.1.1 (Java Repository Master Branch)
- [ ] Bug exists in Snapshot Version 1.1.2-SNAPSHOT (Android Service Repository Master Branch)
- [ ] Bug is just in the Sample Application.

__Android API Version Bug Seen on:__

__Android Version Bug Seen on:__.mqttv3:1.2.0 

Please also check that if you have found the bug in the Release version (1.1.1) that you check that it also exists in the Snapshot (1.1.2-SNAPSHOT) before raising a bug.

## Description of Bug:
E.g. Steps to re-create, how often does this happen etc..

## Console Log output (if available):
07-26 14:23:35.230 W/System.err( 1187): MqttException (0) - java.io.FileNotFoundException: /mnt/sdcard/Android/data/com.iflytek.autofly.feedback/files/MqttConnection/1__631e8f988bbdcbe3-sslusercomp1mycherycom10075/s-8.msg: open failed: ENOENT (No such file or directory)

07-26 14:23:35.231 W/System.err( 1187): 	at org.eclipse.paho.client.mqttv3.persist.MqttDefaultFilePersistence.put(MqttDefaultFilePersistence.java:188)

07-26 14:23:35.231 W/System.err( 1187): 	at org.eclipse.paho.client.mqttv3.internal.ClientState.send(ClientState.java:527)

07-26 14:23:35.231 W/System.err( 1187): 	at org.eclipse.paho.client.mqttv3.internal.ClientComms.internalSend(ClientComms.java:158)

07-26 14:23:35.231 W/System.err( 1187): 	at org.eclipse.paho.client.mqttv3.internal.ClientComms.sendNoWait(ClientComms.java:187)

07-26 14:23:35.232 W/System.err( 1187): 	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.publish(MqttAsyncClient.java:1355)

07-26 14:23:35.232 W/System.err( 1187): 	at org.eclipse.paho.android.service.MqttConnection.publish(MqttConnection.java:579)

07-26 14:23:35.232 W/System.err( 1187): 	at org.eclipse.paho.android.service.MqttService.publish(MqttService.java:468)

07-26 14:23:35.232 W/System.err( 1187): 	at org.eclipse.paho.android.service.MqttAndroidClient.publish(MqttAndroidClient.java:815)

**Comment by hannesa2** [comment]
Does it happen with https://github.com/hannesa2/paho.mqtt.android too ?
