### ISSUE TITLE
Maximum limit of concurrent alarms 500 reached for uid in Samsung

### ISSUE THREAD

**Issue by yuzhijun** [eclipse/paho.mqtt.android#468]
Please fill out the form below before submitting, thank you!
Only occurred in samsung mobile phone. 
Android Version Bug Seen on: 11.0.
I am using android service version 1.1.1 and mqtt client version 1.2.0.

**Description of Bug:**
I have brought mqtt android application in my project, but encountered a wired issue, like that below:
```
Process Name: 'com.hupu.games'
Thread Name: 'pool-39-thread-1'
Back traces starts.
java.lang.IllegalStateException: Maximum limit of concurrent alarms 500 reached for uid: u0a313, callingPackage: 
com.hupu.games
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2393)
	at android.os.Parcel.createException(Parcel.java:2369)
	at android.os.Parcel.readException(Parcel.java:2352)
	at android.os.Parcel.readException(Parcel.java:2294)
	at android.app.IAlarmManager$Stub$Proxy.set(IAlarmManager.java:338)
	at android.app.AlarmManager.setImpl(AlarmManager.java:725)
	at android.app.AlarmManager.setExact(AlarmManager.java:570)
	at androidx.work.impl.utils.ForceStopRunnable.b(ForceStopRunnable.java:5)
	at androidx.work.impl.utils.ForceStopRunnable.isForceStopped(ForceStopRunnable.java:2)
	at androidx.work.impl.utils.ForceStopRunnable.run(ForceStopRunnable.java:8)
	at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:1)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.AlarmManagerService.setImpl(AlarmManagerService.java:2021)
	at com.android.server.AlarmManagerService$4.set(AlarmManagerService.java:2440)
	at android.app.IAlarmManager$Stub.onTransact(IAlarmManager.java:186)
	at android.os.Binder.execTransactInternal(Binder.java:1195)
	at android.os.Binder.execTransact(Binder.java:1159)

Back traces ends.
```

This issue may relate closely to `AlarmPingSender`? any revolution to resolve this problem? Thanks.

**Comment by mintheinwin** [comment]
Hi @yuzhijun  Did you found to resolve this issues I have same like this issues. How you have been to solve ?

**Comment by ShaoQunSun** [comment]
any update?
