### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.io.File.delete()' on a null object reference

### ISSUE THREAD

**Issue by seven001** [eclipse/paho.mqtt.android#475]
Please fill out the form below before submitting, thank you!

 Bug exists Release Version 1.2.5 (Java Repository Master Branch)

Thread Name: 'MQTT Rec: cb7b3027222045a186dfe7fc43a9f35f'
Back traces starts.
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.io.File.delete()' on a null object reference
	at i.b.a.a.a.a0.b.clear(MqttDefaultFilePersistence.java:4)
	at org.eclipse.paho.client.mqttv3.internal.ClientState.clearState(ClientState.java:2)
	at org.eclipse.paho.client.mqttv3.internal.ClientState.notifyReceivedAck(ClientState.java:26)
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:22)
	at java.lang.Thread.run(Thread.java:929)
Back traces ends.

What am I going to do？Help

**Comment by emirhangulmez** [comment]
++ still ongoing issue anyone solve?

**Comment by chlbeyond** [comment]
Brother, have you solved this problem? Please help me.
