### ISSUE TITLE
Can't subscribe to topic on Android 14

### ISSUE THREAD

**Issue by ZouZLong** [eclipse/paho.mqtt.android#498]
Is this project compatible with Android 14?

**Comment by sahityadubey** [comment]
No, this repo is not supported anymore.

To resolve android14 issue follow this document
[](https://developer.android.com/about/versions/14/changes/schedule-exact-alarms
)

and to give it a quick try your code is working or not 
enable Alarm and reminder from app info
[](https://developer.android.com/training/scheduling/alarms#exact-user-grant)

**Comment by ZouZLong** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by mayzs** [comment]
适配到 Android 14 , https://github.com/mayzs/paho.mqtt.android

**Comment by ZouZLong** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by wboykron** [comment]
> 适配到 Android 14 , https://github.com/mayzs/paho.mqtt.android

引入出现这个错误Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not find :unspecified:.
     Required by:
         project :app > io.github.mayzs:paho.mqtt.android:1.1.2，大佬如何解决？

**Comment by ZouZLong** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by mayzs** [comment]
> > 适配到 Android 14 , https://github.com/mayzs/paho.mqtt.android
> 
> 引入出现这个错误Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> 
> > Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
> > Could not find :unspecified:.
> > Required by:
> > project :app > io.github.mayzs:paho.mqtt.android:1.1.2，大佬如何解决？


你项目中 gradle版本低, 可以使用 io.github.mayzs:paho.mqtt.android:1.1.2@aar 进行引用

**Comment by wboykron** [comment]
> > > 适配到 Android 14 , https://github.com/mayzs/paho.mqtt.android
> > 
> > 
> > 引入出现这个错误Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> > > Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
> > > Could not find :unspecified:.
> > > Required by:
> > > project :app > io.github.mayzs:paho.mqtt.android:1.1.2，大佬如何解决？
> 
> 你项目中 gradle版本低, 可以使用 io.github.mayzs:paho.mqtt.android:1.1.2@aar 进行引用
引入成功了，连接就出现：
java.lang.IllegalArgumentException: foregroundServiceType 0x00000001 is not a subset of foregroundServiceType attribute 0x00000000 in service element of manifest file

**Comment by mayzs** [comment]
> > > > 适配到 Android 14 , https://github.com/mayzs/paho.mqtt.android
> > > 
> > > 
> > > 引入出现这个错误Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> > > > Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
> > > > Could not find :unspecified:.
> > > > Required by:
> > > > project :app > io.github.mayzs:paho.mqtt.android:1.1.2，大佬如何解决？
> > 
> > 
> > 你项目中 gradle版本低, 可以使用 io.github.mayzs:paho.mqtt.android:1.1.2@aar 进行引用
> > 引入成功了，连接就出现：
> > java.lang.IllegalArgumentException: foregroundServiceType 0x00000001 is not a subset of foregroundServiceType attribute 0x00000000 in service element of manifest file

参考 sample中 manifest 配置Service方式

**Comment by wboykron** [comment]
> > > > > 适配到 Android 14 , https://github.com/mayzs/paho.mqtt.android
> > > > 
> > > > 
> > > > 引入出现这个错误Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> > > > > Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
> > > > > Could not find :unspecified:.
> > > > > Required by:
> > > > > project :app > io.github.mayzs:paho.mqtt.android:1.1.2，大佬如何解决？
> > > 
> > > 
> > > 你项目中 gradle版本低, 可以使用 io.github.mayzs:paho.mqtt.android:1.1.2@aar 进行引用
> > > 引入成功了，连接就出现：
> > > java.lang.IllegalArgumentException: foregroundServiceType 0x00000001 is not a subset of foregroundServiceType attribute 0x00000000 in service element of manifest file
> 
> 参考 sample中 manifest 配置Service方式

感谢，能连接上了，但是心跳时间后就不停重连，报错如下：2024-01-29 16:34:22.091 15893-18934/com.ynnskj.dinggong.member D/AlarmPingSender: Unregister alarmreceiver to MqttServiceGID_dingo@@@PASS0000003bc99ff84eb89d281c5b2b
2024-01-29 16:34:22.127 15893-15893/com.ynnskj.dinggong.member E/mqtt: callback connectionLost
    已断开连接 (32109) - java.io.EOFException
        at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:197)
        at java.lang.Thread.run(Thread.java:1012)
     Caused by: java.io.EOFException
        at java.io.DataInputStream.readByte(DataInputStream.java:275)
        at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92)
        at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:137)
        at java.lang.Thread.run(Thread.java:1012)

**Comment by stelin** [comment]
see https://github.com/QingHeYang/MqttFix

**Comment by ZouZLong** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by Jame1989** [comment]
> > > 适配到 Android 14 , https://github.com/mayzs/paho.mqtt.android
> > 
> > 
> > 引入出现这个错误Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> > > Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
> > > Could not find :unspecified:.
> > > Required by:
> > > project :app > io.github.mayzs:paho.mqtt.android:1.1.2，大佬如何解决？
> 
> 你项目中 gradle版本低, 可以使用 io.github.mayzs:paho.mqtt.android:1.1.2@aar 进行引用

你好，请问我们项目里使用的kotlin插件还是比较老的：1.6.10，运行时就会报错，kotlin版本不匹配，这个有办法不升级使用吗？（因为升级kotlin版本会带来很多依赖库都得修改，涉及业务方过多），报错信息如下：
.gradle/caches/transforms-2/files-2.1/b6c4b4f4d28c98952d7ab8a85397ff1e/jetified-paho.mqtt.android-1.2.1-api.jar!/META-INF/org.eclipse.paho.android.service_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.6.0.
