### ISSUE TITLE
Mqtt Service crash when detect that connection changed from broadcast intent..

### ISSUE THREAD

**Issue by jarpz** [eclipse/paho.mqtt.android#60]
<b>This happens not all the time, this is the log.</b>

Fatal Exception: java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4000010 (has extras) } in org.eclipse.paho.android.service.MqttService$NetworkConnectionIntentReceiver@1ed6a23b
       at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:876)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5343)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.net.NetworkInfo.isAvailable()' on a null object reference
       at org.eclipse.paho.android.service.MqttService.isOnline(MqttService.java:814)
       at org.eclipse.paho.android.service.MqttService$NetworkConnectionIntentReceiver.onReceive(MqttService.java:796)
       at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:866)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5343)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)

**Comment by jpwsutton** [comment]
Hi,
Looks like you might be using a slightly older version of the Android Service, in a previous bug we added a null check to make sure that this shouldn't happen in the future.. Are you using the latest snapshot Jar?

**Comment by jarpz** [comment]
Hi James, Thanks for answer me,  I'm using latest stable version: 1.0.2, Do you recommend use some snapshot for a production environment?

**Comment by jpwsutton** [comment]
So there is always a risk when running a snapshot in a production system, but there have been a lot of improvements and bug fixes so far that are only in the snapshot which you might find solve your problem. We are planning a new full release in May with Eclipse Neon (1.2) that will contain many improvements. However I'd recommend doing some tests first to make sure that you don't have to upgrade your application first in case any of our fixes affect backwards compatibility.
