### ISSUE TITLE
Mqtt Service crash when receive a message and can not cast MqttTokenAndroid to IMqttDeliveryToken

### ISSUE THREAD

**Issue by jarpz** [eclipse/paho.mqtt.android#61]
<b>This happens not all the time, this is the log.</b>

Fatal Exception: java.lang.ClassCastException: org.eclipse.paho.android.service.MqttTokenAndroid cannot be cast to org.eclipse.paho.client.mqttv3.IMqttDeliveryToken
       at org.eclipse.paho.android.service.MqttAndroidClient.messageDeliveredAction(MqttAndroidClient.java:1424)
       at org.eclipse.paho.android.service.MqttAndroidClient.onReceive(MqttAndroidClient.java:1280)
       at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:297)
       at android.support.v4.content.LocalBroadcastManager.access$000(LocalBroadcastManager.java:46)
       at android.support.v4.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:116)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5392)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by jpwsutton** [comment]
Hi, Which version of the library is this error found in? 1.0.2 or the snapshot (1.0.3)?

**Comment by jarpz** [comment]
In both that stack trace was like up, but In Snapshot 1.0.3 (18/03/2016) was here:

Fatal Exception: java.lang.ClassCastException: org.eclipse.paho.android.service.MqttTokenAndroid cannot be cast to org.eclipse.paho.client.mqttv3.IMqttDeliveryToken
       at org.eclipse.paho.android.service.MqttAndroidClient.messageDeliveredAction(MqttAndroidClient.java:1539)
       at org.eclipse.paho.android.service.MqttAndroidClient.onReceive(MqttAndroidClient.java:1387)
       at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:297)
       at android.support.v4.content.LocalBroadcastManager.access$000(LocalBroadcastManager.java:46)
       at android.support.v4.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:116)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5371)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by jpwsutton** [comment]
This looks like it could definitely be a bug, there doesn't seem anything broken about the cast here: https://github.com/eclipse/paho.mqtt.android/blob/1518ec4f5487fcd7a7cebfe1a0609fc2d571ec93/org.eclipse.paho.android.service/src/main/java/org/eclipse/paho/android/service/MqttAndroidClient.java#L1539

@jarpz could you share any detail about the message that you are receiving that causes this Exception? Can you recreate this with a specific payload or combination of message settings e.g. QoS?

**Comment by jarpz** [comment]
@jpwsutton 

Well, it is hard to reproduce, because it happens in some devices, here the [crashlytics](http://crashes.to/s/afa9a9aecd7) log for paho 1.0.3.. for the paho version 1.0.2 this is the [crashlytis](http://crashes.to/s/1f7a4cee8ef) log, So we think the error is old, you could check it.

We are using [mosquitto](http://mosquitto.org) as broker with SSL encryption, but without encryption also happens

We use QoS 0, the payload are string in json format..

**Comment by jarpz** [comment]
@jpwsutton 

We think, one possible solution could be check if **token** is instance of **IMqttDeliveryToken** before use it..

**Comment by jarpz** [comment]
@jpwsutton 

I implemented this solution:

```
private void messageDeliveredAction(Bundle data) {
		IMqttToken token = removeMqttToken(data);
		if (token != null) {
			if (callback != null) {
				Status status = (Status) data
						.getSerializable(MqttServiceConstants.CALLBACK_STATUS);
				if (status == Status.OK && token instanceof IMqttDeliveryToken) {
					callback.deliveryComplete((IMqttDeliveryToken) token);
				}
			}
		}
	}
```
 **&& token instanceof IMqttDeliveryToken**

 I don't know if this is the correct & final solution but I could solve my problem

**Comment by jpwsutton** [comment]
@jarpz I aggree, I've had a look through and I think we probably should have been checking this anyway. I've merged the change in, but there won't be a build SNAPSHOT jar available yet. I'll comment on this issue when one is available.
