### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by laoyang** [eclipse/paho.mqtt.android#99]
```
                                                                        Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Object.hashCode()' on a null object reference
                                                                           at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:772)
                                                                           at org.eclipse.paho.android.service.MqttService.getConnection(MqttService.java:560)
                                                                           at org.eclipse.paho.android.service.MqttService.isConnected(MqttService.java:407)
                                                                           at org.eclipse.paho.android.service.MqttAndroidClient.isConnected(MqttAndroidClient.java:245)
```

Please fill out the form below before submitting, thank you!
- [x] Bug exists Release Version 1.1.0 (Java Repository Master Branch)
- [ ] Bug exists in Snapshot Version 1.1.1-SNAPSHOT (Android Service Repository Master Branch)
- [ ] Bug is just in the Sample Application.

**Android API Version Bug Seen on:**

**Android Version Bug Seen on:**

Please also check that if you have found the bug in the Release version (1.1.0) that you check that it also exists in the Snapshot (1.1.1-SNAPSHOT) before raising a bug.
## Description of Bug:

E.g. Steps to re-create, how often does this happen etc..

**Comment by jpwsutton** [comment]
@laoyang Are you able to duplicate this in the SNAPSHOT build? And do you have any steps to recreate?

**Comment by jpwsutton** [comment]
Closing as no response since 2016.

**Comment by Raja-Raman** [comment]
I observe this crash consistently as of July 2018:
Please suggest any work around.

Android SDK version 26, target version 26.

MqttAndroidClient client;
client.connect(..);
  // do stuff
client.disconnect();
if (client==null)
    return;
if (client.isConnected()) {  /* crashes here */   
   // do stuff
} 

The error message is:
07-13 23:45:53.445 5565-5565/com.raja.mqttsms1 W/System.err: java.lang.NullPointerException: Attempt to 
invoke virtual method 'int java.lang.Object.hashCode()' on a null object reference
        at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:772)
        at org.eclipse.paho.android.service.MqttService.getConnection(MqttService.java:560)
        at org.eclipse.paho.android.service.MqttService.isConnected(MqttService.java:407)
        at org.eclipse.paho.android.service.MqttAndroidClient.isConnected(MqttAndroidClient.java:245)
        at com.raja.mqttsms1.MainActivity.connect(MainActivity.java:97)
        at com.raja.mqttsms1.MainActivity.onResume(MainActivity.java:293)

**Comment by wv1124** [comment]
> I observe this crash consistently as of July 2018: Please suggest any work around.
> 
> Android SDK version 26, target version 26.
> 
> MqttAndroidClient client; client.connect(..); // do stuff client.disconnect(); if (client==null) return; if (client.isConnected()) { /* crashes here */ // do stuff }
> 
> The error message is: 07-13 23:45:53.445 5565-5565/com.raja.mqttsms1 W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Object.hashCode()' on a null object reference at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:772) at org.eclipse.paho.android.service.MqttService.getConnection(MqttService.java:560) at org.eclipse.paho.android.service.MqttService.isConnected(MqttService.java:407) at org.eclipse.paho.android.service.MqttAndroidClient.isConnected(MqttAndroidClient.java:245) at com.raja.mqttsms1.MainActivity.connect(MainActivity.java:97) at com.raja.mqttsms1.MainActivity.onResume(MainActivity.java:293)

when disconect: 

                    mMqttClient.unsubscribe(this.topic);
//                    mMqttClient.disconnect();
                    mMqttClient.close();
                    mMqttClient.unregisterResources();
                    mMqttClient = null;
 then isConnected() will not throw  Invalid ClientHandle Exception
